### ISSUE TITLE
Error in this function in file *github.com/kataras/iris/view/django.go*

### ISSUE THREAD

**Issue by Ekuzkamaza** [kataras/iris#1253]
// getPongoContext returns the pongo2.Context from map[string]interface{} or from pongo2.Context, used internaly

```go
func getPongoContext(templateData interface{}) pongo2.Context {
if templateData == nil {
return nil
}

if contextData, isPongoContext := templateData.(pongo2.Context); isPongoContext {
return contextData
}

if contextData, isContextViewData := templateData.(context.Map); isContextViewData {
return pongo2.Context(contextData)
}

return templateData.(map[string]interface{})
}
```
with error **[HTTP Server] http: panic serving [::1]:49279: interface conversion: interface {} is app.err, not map[string]interface {}**

**Comment by kataras** [comment]
where `app.err` is coming from?

**Comment by vfrank66** [comment]
Also getting this error running for VS Code

> monitor-api/vendor/github.com/kataras/iris/view
> vendor/github.com/kataras/iris/view/django.go:225:27: pongo2.RegisterTag(tagName, fn) used as value
> vendor/github.com/kataras/iris/view/django.go:253:19: undefined: pongo2.NewLocalFileSystemLoader
> vendor/github.com/kataras/iris/view/django.go:258:22: too many arguments in call to pongo2.NewSet
> vendor/github.com/kataras/iris/view/django.go:311:22: too many arguments in call to pongo2.NewSet
> 	have (string, *tDjangoAssetLoader)
> 	want (string)
> exit status 2
> Process exiting with code: 1

main.go
package main
```go
import (
	"github.com/kataras/iris"
	"github.com/kataras/iris/context"
)

func main() {
	app := iris.Default()
	app.Get("/ping", func(ctx iris.Context) {
		ctx.JSON(iris.Map{
			"message": "pong",
		})
	})
	// listen and serve on http://0.0.0.0:8080.
	app.Run(iris.Addr(":8080"))
} 
```

**Comment by Ekuzkamaza** [comment]
```
Now listening on: http://localhost:3333
Application started. Press CTRL+C to shut down.
[HTTP Server] http: panic serving [::1]:50650: interface conversion: interface {} is app.err, not map[string]interface {}
goroutine 60 [running]:
net/http.(*conn).serve.func1(0xc0001a8f00)
	D:/serv/go/src/net/http/server.go:1769 +0xd0
panic(0xa686c0, 0xc0002d3c50)
	D:/serv/go/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/view.getPongoContext(...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:373
github.com/kataras/iris/view.(*DjangoEngine).ExecuteWriter(0xc0003309a0, 0xc22860, 0xc000078570, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000005760, 0x0, ...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:404 +0x2c8
github.com/kataras/iris/view.(*View).ExecuteWriter(0xc000311a98, 0xc22860, 0xc000078570, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000005760, 0xc00013d901, ...)
	D:/proj/go/src/github.com/kataras/iris/view/view.go:57 +0x10b
github.com/kataras/iris.(*Application).View(0xc000311a70, 0xc22860, 0xc000078570, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000005760, 0xa8b5a0, ...)
	D:/proj/go/src/github.com/kataras/iris/iris.go:331 +0xc2
github.com/kataras/iris/context.(*context).View(0xc0001aa750, 0xb23d4b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:2726 +0x1b8
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc0001aa750)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
github.com/kataras/iris/context.Do(0xc41fa0, 0xc0001aa750, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:922 +0x88
github.com/kataras/iris/context.(*context).Do(0xc0001aa750, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1094 +0x5c
github.com/kataras/iris/core/router.(*ErrorCodeHandler).Fire(0xc0003285a0, 0xc41fa0, 0xc0001aa750)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:65 +0xf5
github.com/kataras/iris/core/router.(*ErrorCodeHandlers).Fire(0xc00032c8e0, 0xc41fa0, 0xc0001aa750)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:159 +0xa4
github.com/kataras/iris/core/router.(*APIBuilder).FireErrorCode(0xc000494480, 0xc41fa0, 0xc0001aa750)
	D:/proj/go/src/github.com/kataras/iris/core/router/api_builder.go:863 +0x4a
github.com/kataras/iris/context.(*context).EndRequest(0xc0001aa750)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1045 +0x119
github.com/kataras/iris/context.(*Pool).Release(0xc0002cb200, 0xc41fa0, 0xc0001aa750)
	D:/proj/go/src/github.com/kataras/iris/context/pool.go:44 +0x38
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0xc2fd60, 0xc0002fa0e0, 0xc000082300)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:85 +0xb8
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc00026b040, 0xc2fd60, 0xc0002fa0e0, 0xc000082300)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:161 +0x4f
net/http.serverHandler.ServeHTTP(0xc0001b60d0, 0xc2fd60, 0xc0002fa0e0, 0xc000082300)
	D:/serv/go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc0001a8f00, 0xc31560, 0xc0000261c0)
	D:/serv/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	D:/serv/go/src/net/http/server.go:2884 +0x2fb
[HTTP Server] http: panic serving [::1]:50656: interface conversion: interface {} is app.err, not map[string]interface {}
goroutine 83 [running]:
net/http.(*conn).serve.func1(0xc000067180)
	D:/serv/go/src/net/http/server.go:1769 +0xd0
panic(0xa686c0, 0xc00034f380)
	D:/serv/go/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/view.getPongoContext(...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:373
github.com/kataras/iris/view.(*DjangoEngine).ExecuteWriter(0xc0003309a0, 0xc22860, 0xc0002d3dd0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000462240, 0x0, ...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:404 +0x2c8
github.com/kataras/iris/view.(*View).ExecuteWriter(0xc000311a98, 0xc22860, 0xc0002d3dd0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000462240, 0xc000555901, ...)
	D:/proj/go/src/github.com/kataras/iris/view/view.go:57 +0x10b
github.com/kataras/iris.(*Application).View(0xc000311a70, 0xc22860, 0xc0002d3dd0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000462240, 0xa8b5a0, ...)
	D:/proj/go/src/github.com/kataras/iris/iris.go:331 +0xc2
github.com/kataras/iris/context.(*context).View(0xc0003805a0, 0xb23d4b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:2726 +0x1b8
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc0003805a0)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
github.com/kataras/iris/context.Do(0xc41fa0, 0xc0003805a0, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:922 +0x88
github.com/kataras/iris/context.(*context).Do(0xc0003805a0, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1094 +0x5c
github.com/kataras/iris/core/router.(*ErrorCodeHandler).Fire(0xc0003285a0, 0xc41fa0, 0xc0003805a0)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:65 +0xf5
github.com/kataras/iris/core/router.(*ErrorCodeHandlers).Fire(0xc00032c8e0, 0xc41fa0, 0xc0003805a0)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:159 +0xa4
github.com/kataras/iris/core/router.(*APIBuilder).FireErrorCode(0xc000494480, 0xc41fa0, 0xc0003805a0)
	D:/proj/go/src/github.com/kataras/iris/core/router/api_builder.go:863 +0x4a
github.com/kataras/iris/context.(*context).EndRequest(0xc0003805a0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1045 +0x119
github.com/kataras/iris/context.(*Pool).Release(0xc0002cb200, 0xc41fa0, 0xc0003805a0)
	D:/proj/go/src/github.com/kataras/iris/context/pool.go:44 +0x38
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0xc2fd60, 0xc0002fa1c0, 0xc00009ed00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:85 +0xb8
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc00026b040, 0xc2fd60, 0xc0002fa1c0, 0xc00009ed00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:161 +0x4f
net/http.serverHandler.ServeHTTP(0xc0001b60d0, 0xc2fd60, 0xc0002fa1c0, 0xc00009ed00)
	D:/serv/go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc000067180, 0xc31560, 0xc0004fff40)
	D:/serv/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	D:/serv/go/src/net/http/server.go:2884 +0x2fb
[HTTP Server] http: panic serving [::1]:50655: interface conversion: interface {} is app.err, not map[string]interface {}
goroutine 82 [running]:
net/http.(*conn).serve.func1(0xc000066c80)
	D:/serv/go/src/net/http/server.go:1769 +0xd0
panic(0xa686c0, 0xc000079ad0)
	D:/serv/go/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/view.getPongoContext(...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:373
github.com/kataras/iris/view.(*DjangoEngine).ExecuteWriter(0xc0003309a0, 0xc22860, 0xc000328090, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc00034a020, 0x0, ...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:404 +0x2c8
github.com/kataras/iris/view.(*View).ExecuteWriter(0xc000311a98, 0xc22860, 0xc000328090, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc00034a020, 0xc000553901, ...)
	D:/proj/go/src/github.com/kataras/iris/view/view.go:57 +0x10b
github.com/kataras/iris.(*Application).View(0xc000311a70, 0xc22860, 0xc000328090, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc00034a020, 0xa8b5a0, ...)
	D:/proj/go/src/github.com/kataras/iris/iris.go:331 +0xc2
github.com/kataras/iris/context.(*context).View(0xc00046c090, 0xb23d4b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:2726 +0x1b8
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc00046c090)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
github.com/kataras/iris/context.Do(0xc41fa0, 0xc00046c090, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:922 +0x88
github.com/kataras/iris/context.(*context).Do(0xc00046c090, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1094 +0x5c
github.com/kataras/iris/core/router.(*ErrorCodeHandler).Fire(0xc0003285a0, 0xc41fa0, 0xc00046c090)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:65 +0xf5
github.com/kataras/iris/core/router.(*ErrorCodeHandlers).Fire(0xc00032c8e0, 0xc41fa0, 0xc00046c090)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:159 +0xa4
github.com/kataras/iris/core/router.(*APIBuilder).FireErrorCode(0xc000494480, 0xc41fa0, 0xc00046c090)
	D:/proj/go/src/github.com/kataras/iris/core/router/api_builder.go:863 +0x4a
github.com/kataras/iris/context.(*context).EndRequest(0xc00046c090)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1045 +0x119
github.com/kataras/iris/context.(*Pool).Release(0xc0002cb200, 0xc41fa0, 0xc00046c090)
	D:/proj/go/src/github.com/kataras/iris/context/pool.go:44 +0x38
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0xc2fd60, 0xc000470000, 0xc00009ec00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:85 +0xb8
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc00026b040, 0xc2fd60, 0xc000470000, 0xc00009ec00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:161 +0x4f
net/http.serverHandler.ServeHTTP(0xc0001b60d0, 0xc2fd60, 0xc000470000, 0xc00009ec00)
	D:/serv/go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc000066c80, 0xc31560, 0xc0004ffe00)
	D:/serv/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	D:/serv/go/src/net/http/server.go:2884 +0x2fb
[HTTP Server] http: panic serving [::1]:50654: interface conversion: interface {} is app.err, not map[string]interface {}
goroutine 33 [running]:
net/http.(*conn).serve.func1(0xc000066500)
	D:/serv/go/src/net/http/server.go:1769 +0xd0
panic(0xa686c0, 0xc000113050)
	D:/serv/go/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/view.getPongoContext(...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:373
github.com/kataras/iris/view.(*DjangoEngine).ExecuteWriter(0xc0003309a0, 0xc22860, 0xc0002d3f80, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000462280, 0x0, ...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:404 +0x2c8
github.com/kataras/iris/view.(*View).ExecuteWriter(0xc000311a98, 0xc22860, 0xc0002d3f80, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000462280, 0xc000521901, ...)
	D:/proj/go/src/github.com/kataras/iris/view/view.go:57 +0x10b
github.com/kataras/iris.(*Application).View(0xc000311a70, 0xc22860, 0xc0002d3f80, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000462280, 0xa8b5a0, ...)
	D:/proj/go/src/github.com/kataras/iris/iris.go:331 +0xc2
github.com/kataras/iris/context.(*context).View(0xc0003806c0, 0xb23d4b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:2726 +0x1b8
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc0003806c0)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
github.com/kataras/iris/context.Do(0xc41fa0, 0xc0003806c0, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:922 +0x88
github.com/kataras/iris/context.(*context).Do(0xc0003806c0, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1094 +0x5c
github.com/kataras/iris/core/router.(*ErrorCodeHandler).Fire(0xc0003285a0, 0xc41fa0, 0xc0003806c0)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:65 +0xf5
github.com/kataras/iris/core/router.(*ErrorCodeHandlers).Fire(0xc00032c8e0, 0xc41fa0, 0xc0003806c0)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:159 +0xa4
github.com/kataras/iris/core/router.(*APIBuilder).FireErrorCode(0xc000494480, 0xc41fa0, 0xc0003806c0)
	D:/proj/go/src/github.com/kataras/iris/core/router/api_builder.go:863 +0x4a
github.com/kataras/iris/context.(*context).EndRequest(0xc0003806c0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1045 +0x119
github.com/kataras/iris/context.(*Pool).Release(0xc0002cb200, 0xc41fa0, 0xc0003806c0)
	D:/proj/go/src/github.com/kataras/iris/context/pool.go:44 +0x38
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0xc2fd60, 0xc0002fa2a0, 0xc00009eb00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:85 +0xb8
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc00026b040, 0xc2fd60, 0xc0002fa2a0, 0xc00009eb00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:161 +0x4f
net/http.serverHandler.ServeHTTP(0xc0001b60d0, 0xc2fd60, 0xc0002fa2a0, 0xc00009eb00)
	D:/serv/go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc000066500, 0xc31560, 0xc0004ffd40)
	D:/serv/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	D:/serv/go/src/net/http/server.go:2884 +0x2fb
[HTTP Server] http: panic serving [::1]:50653: interface conversion: interface {} is app.err, not map[string]interface {}
goroutine 32 [running]:
net/http.(*conn).serve.func1(0xc000066280)
	D:/serv/go/src/net/http/server.go:1769 +0xd0
panic(0xa686c0, 0xc0002d2900)
	D:/serv/go/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/view.getPongoContext(...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:373
github.com/kataras/iris/view.(*DjangoEngine).ExecuteWriter(0xc0003309a0, 0xc22860, 0xc00034e090, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc0004622a0, 0x0, ...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:404 +0x2c8
github.com/kataras/iris/view.(*View).ExecuteWriter(0xc000311a98, 0xc22860, 0xc00034e090, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc0004622a0, 0xc000557901, ...)
	D:/proj/go/src/github.com/kataras/iris/view/view.go:57 +0x10b
github.com/kataras/iris.(*Application).View(0xc000311a70, 0xc22860, 0xc00034e090, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc0004622a0, 0xa8b5a0, ...)
	D:/proj/go/src/github.com/kataras/iris/iris.go:331 +0xc2
github.com/kataras/iris/context.(*context).View(0xc0003807e0, 0xb23d4b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:2726 +0x1b8
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc0003807e0)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
github.com/kataras/iris/context.Do(0xc41fa0, 0xc0003807e0, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:922 +0x88
github.com/kataras/iris/context.(*context).Do(0xc0003807e0, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1094 +0x5c
github.com/kataras/iris/core/router.(*ErrorCodeHandler).Fire(0xc0003285a0, 0xc41fa0, 0xc0003807e0)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:65 +0xf5
github.com/kataras/iris/core/router.(*ErrorCodeHandlers).Fire(0xc00032c8e0, 0xc41fa0, 0xc0003807e0)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:159 +0xa4
github.com/kataras/iris/core/router.(*APIBuilder).FireErrorCode(0xc000494480, 0xc41fa0, 0xc0003807e0)
	D:/proj/go/src/github.com/kataras/iris/core/router/api_builder.go:863 +0x4a
github.com/kataras/iris/context.(*context).EndRequest(0xc0003807e0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1045 +0x119
github.com/kataras/iris/context.(*Pool).Release(0xc0002cb200, 0xc41fa0, 0xc0003807e0)
	D:/proj/go/src/github.com/kataras/iris/context/pool.go:44 +0x38
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0xc2fd60, 0xc0002fa380, 0xc00009ea00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:85 +0xb8
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc00026b040, 0xc2fd60, 0xc0002fa380, 0xc00009ea00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:161 +0x4f
net/http.serverHandler.ServeHTTP(0xc0001b60d0, 0xc2fd60, 0xc0002fa380, 0xc00009ea00)
	D:/serv/go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc000066280, 0xc31560, 0xc0004ffc80)
	D:/serv/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	D:/serv/go/src/net/http/server.go:2884 +0x2fb
[HTTP Server] http: panic serving [::1]:50652: interface conversion: interface {} is app.err, not map[string]interface {}
goroutine 31 [running]:
net/http.(*conn).serve.func1(0xc0000661e0)
	D:/serv/go/src/net/http/server.go:1769 +0xd0
panic(0xa686c0, 0xc00034fef0)
	D:/serv/go/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/view.getPongoContext(...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:373
github.com/kataras/iris/view.(*DjangoEngine).ExecuteWriter(0xc0003309a0, 0xc22860, 0xc00034e1e0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc0004622e0, 0x0, ...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:404 +0x2c8
github.com/kataras/iris/view.(*View).ExecuteWriter(0xc000311a98, 0xc22860, 0xc00034e1e0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc0004622e0, 0xc000303901, ...)
	D:/proj/go/src/github.com/kataras/iris/view/view.go:57 +0x10b
github.com/kataras/iris.(*Application).View(0xc000311a70, 0xc22860, 0xc00034e1e0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc0004622e0, 0xa8b5a0, ...)
	D:/proj/go/src/github.com/kataras/iris/iris.go:331 +0xc2
github.com/kataras/iris/context.(*context).View(0xc000380900, 0xb23d4b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:2726 +0x1b8
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc000380900)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
github.com/kataras/iris/context.Do(0xc41fa0, 0xc000380900, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:922 +0x88
github.com/kataras/iris/context.(*context).Do(0xc000380900, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1094 +0x5c
github.com/kataras/iris/core/router.(*ErrorCodeHandler).Fire(0xc0003285a0, 0xc41fa0, 0xc000380900)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:65 +0xf5
github.com/kataras/iris/core/router.(*ErrorCodeHandlers).Fire(0xc00032c8e0, 0xc41fa0, 0xc000380900)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:159 +0xa4
github.com/kataras/iris/core/router.(*APIBuilder).FireErrorCode(0xc000494480, 0xc41fa0, 0xc000380900)
	D:/proj/go/src/github.com/kataras/iris/core/router/api_builder.go:863 +0x4a
github.com/kataras/iris/context.(*context).EndRequest(0xc000380900)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1045 +0x119
github.com/kataras/iris/context.(*Pool).Release(0xc0002cb200, 0xc41fa0, 0xc000380900)
	D:/proj/go/src/github.com/kataras/iris/context/pool.go:44 +0x38
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0xc2fd60, 0xc0002fa460, 0xc00009e900)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:85 +0xb8
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc00026b040, 0xc2fd60, 0xc0002fa460, 0xc00009e900)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:161 +0x4f
net/http.serverHandler.ServeHTTP(0xc0001b60d0, 0xc2fd60, 0xc0002fa460, 0xc00009e900)
	D:/serv/go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc0000661e0, 0xc31560, 0xc0004ffc00)
	D:/serv/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	D:/serv/go/src/net/http/server.go:2884 +0x2fb
[HTTP Server] http: panic serving [::1]:50657: interface conversion: interface {} is app.err, not map[string]interface {}
goroutine 63 [running]:
net/http.(*conn).serve.func1(0xc0001a8280)
	D:/serv/go/src/net/http/server.go:1769 +0xd0
panic(0xa686c0, 0xc0001110e0)
	D:/serv/go/src/runtime/panic.go:522 +0x1c3
github.com/kataras/iris/view.getPongoContext(...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:373
github.com/kataras/iris/view.(*DjangoEngine).ExecuteWriter(0xc0003309a0, 0xc22860, 0xc0002b92c0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000120c00, 0x0, ...)
	D:/proj/go/src/github.com/kataras/iris/view/django.go:404 +0x2c8
github.com/kataras/iris/view.(*View).ExecuteWriter(0xc000311a98, 0xc22860, 0xc0002b92c0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000120c00, 0xc000305901, ...)
	D:/proj/go/src/github.com/kataras/iris/view/view.go:57 +0x10b
github.com/kataras/iris.(*Application).View(0xc000311a70, 0xc22860, 0xc0002b92c0, 0xb23d4b, 0x11, 0x0, 0x0, 0xa8b5a0, 0xc000120c00, 0xa8b5a0, ...)
	D:/proj/go/src/github.com/kataras/iris/iris.go:331 +0xc2
github.com/kataras/iris/context.(*context).View(0xc00035b320, 0xb23d4b, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:2726 +0x1b8
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc00035b320)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
github.com/kataras/iris/context.Do(0xc41fa0, 0xc00035b320, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:922 +0x88
github.com/kataras/iris/context.(*context).Do(0xc00035b320, 0xc000130210, 0x1, 0x1)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1094 +0x5c
github.com/kataras/iris/core/router.(*ErrorCodeHandler).Fire(0xc0003285a0, 0xc41fa0, 0xc00035b320)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:65 +0xf5
github.com/kataras/iris/core/router.(*ErrorCodeHandlers).Fire(0xc00032c8e0, 0xc41fa0, 0xc00035b320)
	D:/proj/go/src/github.com/kataras/iris/core/router/status.go:159 +0xa4
github.com/kataras/iris/core/router.(*APIBuilder).FireErrorCode(0xc000494480, 0xc41fa0, 0xc00035b320)
	D:/proj/go/src/github.com/kataras/iris/core/router/api_builder.go:863 +0x4a
github.com/kataras/iris/context.(*context).EndRequest(0xc00035b320)
	D:/proj/go/src/github.com/kataras/iris/context/context.go:1045 +0x119
github.com/kataras/iris/context.(*Pool).Release(0xc0002cb200, 0xc41fa0, 0xc00035b320)
	D:/proj/go/src/github.com/kataras/iris/context/pool.go:44 +0x38
github.com/kataras/iris/core/router.(*Router).BuildRouter.func1(0xc2fd60, 0xc0004f21c0, 0xc000082a00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:85 +0xb8
github.com/kataras/iris/core/router.(*Router).ServeHTTP(0xc00026b040, 0xc2fd60, 0xc0004f21c0, 0xc000082a00)
	D:/proj/go/src/github.com/kataras/iris/core/router/router.go:161 +0x4f
net/http.serverHandler.ServeHTTP(0xc0001b60d0, 0xc2fd60, 0xc0004f21c0, 0xc000082a00)
	D:/serv/go/src/net/http/server.go:2774 +0xb2
net/http.(*conn).serve(0xc0001a8280, 0xc31560, 0xc000483ec0)
	D:/serv/go/src/net/http/server.go:1878 +0x853
created by net/http.(*Server).Serve
	D:/serv/go/src/net/http/server.go:2884 +0x2fb
```

**Comment by Ekuzkamaza** [comment]
error after call this function
```
func (vc *DashboardController) Get(ctx iris.Context) {
    ctx.View("pull/dashboard.html")
}
```

**Comment by kataras** [comment]
OK, @Ekuzkamaza , django's context is a `map[string] interface{}`, by the engine's designers, it can't be a custom type, I see your `app.error` in the logs which this whole error comes from your project's code: 

```sh
_/D_/proj/go/src/github.com/mintjoy/oso/app.onError(0xc41fa0, 0xc0001aa750)
	D:/proj/go/src/github.com/mintjoy/oso/app/main.go:91 +0x103
```

Try changing this to a `map[string] interface{ "error": yourErr}` instead. It's not an iris issue.
