### ISSUE TITLE
reflect: Call with too few input arguments [BUG]

### ISSUE THREAD

**Issue by r3eg** [kataras/iris#1428]
Hello Makis!

Just have after update to iris v.12.1.4 this panic:
`reflect: Call with too few input arguments
goroutine 14789 [running]:
net/http.(*conn).serve.func1(0xc0008ffa40)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1094420, 0x1564cd0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.call(0xc000563da0, 0xc00067ee70, 0x13, 0x12a09da, 0x4, 0xc0005f6460, 0x1, 0x1, 0xc00090eea0, 0x12a5fd9, ...)
        /usr/local/go/src/reflect/value.go:377 +0x1530
reflect.Value.Call(0xc000563da0, 0xc00067ee70, 0x13, 0xc0005f6460, 0x1, 0x1, 0x88d6e100, 0xc0005ef8d0, 0x203000)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handlerOf.func1(0x15cc300, 0xc00090eea0)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/mvc/controller.go:451 +0x5a
github.com/kataras/iris/v12/context.(*context).Proceed(0xc00090eea0, 0xc0005f64e0, 0x469d80)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/context/context.go:1288 +0x48
github.com/kataras/iris/v12/core/router.ExecutionOptions.buildHandler.func1(0x15cc300, 0xc00090eea0)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/core/router/handler_execution_rules.go:90 +0x3d
github.com/kataras/iris/v12/context.DefaultNext(0x15cc300, 0xc00090eea0)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/context/context.go:1336 +0x107
github.com/kataras/iris/v12/context.(*context).Next(0xc00090eea0)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/context/context.go:1345 +0x3e
main.main.func2(0x15cc300, 0xc00090eea0)
        /go/src/api/src/main.go:1031 +0x94
github.com/kataras/iris/v12/context.Do(0x15cc300, 0xc00090eea0, 0xc00060d540, 0x3, 0x4)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/context/context.go:1023 +0x81
github.com/kataras/iris/v12/context.(*context).Do(0xc00090eea0, 0xc00060d540, 0x3, 0x4)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/context/context.go:1210 +0x55
github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc00060c4a0, 0x15cc300, 0xc00090eea0)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/core/router/handler.go:250 +0x556
github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.func1(0x159bdc0, 0xc0009f88c0, 0xc0004b1000)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/core/router/router.go:135 +0x8f
github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0xc00051a370, 0x159bdc0, 0xc0009f88c0, 0xc0004b1000)
        /go/pkg/mod/github.com/kataras/iris/v12@v12.1.4/core/router/router.go:227 +0x48
net/http.serverHandler.ServeHTTP(0xc0004c20e0, 0x159bdc0, 0xc0009f88c0, 0xc0004b1000)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0008ffa40, 0x15a2500, 0xc000754a80)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
`

The problem is coming from this line:
`	app.UseGlobal(func(ctx iris.Context) {
               ........
		ctx.Record()
		ctx.Next()    // main.go 1031
	})
`
What can be the reason of that? 

Best regards, Vlad

**Comment by r3eg** [comment]
Sorry, my mistake....just forgot change iris to iris/v12 in import
