### ISSUE TITLE
[BUG] Update Expiration every visit

### ISSUE THREAD

**Issue by huyinghuan** [kataras/iris#1488]
**Describe the bug**

appliaction   need:

session expire after 30 minute at the last visit

there are test:

```

import (
  "os"
  "sync"
  "testing"
  "time"

  "github.com/kataras/iris/v12"
  "github.com/kataras/iris/v12/httptest"
  "github.com/kataras/iris/v12/sessions"
)

var app *iris.Application
var cookieName = "mycustomsessionid"

func TestMain(m *testing.M){
  // config.Init()
  // database.InitAll()
  sess := sessions.New(sessions.Config{
    Cookie:  cookieName,
    Expires: 30 * time.Minute,
    AllowReclaim: true,
  })

  app = iris.New()

  app.Use(sess.Handler())
  app.Use(func(ctx iris.Context){
    // session will expire after 30 minute at the last visit
    // maybe I use error method ?
    sess.UpdateExpiration(ctx, 30 * time.Minute)
    ctx.Next()
  })

  app.Get("/set", func(ctx iris.Context) {
    sessions.Get(ctx).Set("hello", "world")
    ctx.StatusCode(200)
  })

  app.Get("/get", func(ctx iris.Context) {
    ctx.WriteString(sessions.Get(ctx).GetString("hello"))
  })

  exit := m.Run()
  os.Exit(exit)
}

func TestSessionTimer(t *testing.T){
  e := httptest.New(t, app, httptest.URL("http://example.com"))

  e.GET("/set").Expect().Status(httptest.StatusOK)
  i := 0
 // Simulated concurrent
// Actually In my application， when user loads is 2， the error happen
  wg := sync.WaitGroup{}
  wg.Add(100)
  for i < 100 {
    go func() {
      e.GET("/get").Expect().Status(httptest.StatusOK).Body().Equal("world")
      wg.Done()
    }()
    i++
  }
  wg.Wait()
  e.GET("/get").Expect().Status(httptest.StatusOK).Body().Equal("world")

}

```

Actually In my application， when user loads is 2， the error happen

![image](https://user-images.githubusercontent.com/3005433/79524707-c9a80100-8093-11ea-9264-1cf41374ccbf.png)

**Comment by huyinghuan** [comment]
```
panic: runtime error: racy use of timers

goroutine 89 [running]:
time.resetTimer(0xc000548e68, 0x3eee3422f88fd)
	/usr/local/go/src/runtime/time.go:233 +0x35
time.(*Timer).Reset(0xc000548e60, 0x1a3185c5000, 0x2228f20)
	/usr/local/go/src/time/sleep.go:126 +0x7d
github.com/kataras/iris/v12/sessions.(*LifeTime).Shift(0xc000539358, 0x1a3185c5000)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/sessions/lifetime.go:47 +0x94
github.com/kataras/iris/v12/sessions.(*provider).UpdateExpiration(0xc0002416c0, 0xc00047e2d2, 0x24, 0x1a3185c5000, 0x24, 0x24)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/sessions/provider.go:108 +0xbe
github.com/kataras/iris/v12/sessions.(*Sessions).UpdateExpiration(0xc0005390e0, 0x1bcb9a0, 0xc000782000, 0x1a3185c5000, 0x0, 0x0, 0x0, 0x1, 0xc000539320)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/sessions/sessions.go:149 +0xbd
oauth/controller.TestMain.func1(0x1bcb9a0, 0xc000782000)
	/Users/huyinghuan/go-work/src/oauth/controller/session_timer_test.go:31 +0x5e
github.com/kataras/iris/v12/context.DefaultNext(0x1bcb9a0, 0xc000782000)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/context/context.go:1343 +0x107
github.com/kataras/iris/v12/context.(*context).Next(0xc000782000)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/context/context.go:1352 +0x3e
github.com/kataras/iris/v12/sessions.(*Sessions).Handler.func1(0x1bcb9a0, 0xc000782000)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/sessions/sessions.go:105 +0xdc
github.com/kataras/iris/v12/context.Do(0x1bcb9a0, 0xc000782000, 0xc00028da20, 0x3, 0x3)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/context/context.go:1030 +0x81
github.com/kataras/iris/v12/context.(*context).Do(0xc000782000, 0xc00028da20, 0x3, 0x3)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/context/context.go:1217 +0x55
github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc00028db00, 0x1bcb9a0, 0xc000782000)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/core/router/handler.go:250 +0x556
github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.func1(0x1ba9800, 0xc000542300, 0xc000436800)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/core/router/router.go:135 +0x8f
github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0xc000548c80, 0x1ba9800, 0xc000542300, 0xc000436800)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/kataras/iris/v12/core/router/router.go:227 +0x48
github.com/gavv/httpexpect.Binder.RoundTrip(0x1b995e0, 0xc0004ce3f0, 0x0, 0xc000436800, 0x18e09e0, 0xc000090000, 0x25029b8)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/gavv/httpexpect/binder.go:62 +0x14c
net/http.send(0xc000436800, 0x1b9abc0, 0xc00028dbe0, 0x0, 0x0, 0x0, 0xc000438118, 0x1a2eefc, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:252 +0x43e
net/http.(*Client).send(0xc0002b7290, 0xc000436800, 0x0, 0x0, 0x0, 0xc000438118, 0x0, 0x1, 0x1b7dcaa)
	/usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).do(0xc0002b7290, 0xc000436800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:699 +0x44a
net/http.(*Client).Do(0xc0002b7290, 0xc000436800, 0x10c3c56, 0x5e9910ea, 0xe1e51a0)
	/usr/local/go/src/net/http/client.go:567 +0x35
github.com/gavv/httpexpect.(*Request).sendRequest(0xc000436900, 0xf135f6)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/gavv/httpexpect/request.go:983 +0x4e
github.com/gavv/httpexpect.(*Request).roundTrip(0xc000436900, 0xc000610f40)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/gavv/httpexpect/request.go:906 +0x359
github.com/gavv/httpexpect.(*Request).Expect(0xc000436900, 0x1a1ed6a)
	/Users/huyinghuan/go-work/src/oauth/vendor/github.com/gavv/httpexpect/request.go:866 +0x43
oauth/controller.TestSessionTimer.func1(0xc0002b3ae0, 0xc00009fcc0)
	/Users/huyinghuan/go-work/src/oauth/controller/session_timer_test.go:57 +0x7b
created by oauth/controller.TestSessionTimer
	/Users/huyinghuan/go-work/src/oauth/controller/session_timer_test.go:56 +0x17a

Process finished with exit code 1

```

**Comment by huyinghuan** [comment]
set expires `0` when config.

 Test pass.

```
package controller

import (
  "os"
  "sync"
  "testing"
  "time"

  "github.com/kataras/iris/v12"
  "github.com/kataras/iris/v12/httptest"
  "github.com/kataras/iris/v12/sessions"
)

var app *iris.Application
var cookieName = "mycustomsessionid"

func TestMain(m *testing.M){
  // config.Init()
  // database.InitAll()
  sess := sessions.New(sessions.Config{
    Cookie:  cookieName,
    Expires: 0,
    AllowReclaim: true,
  })

  app = iris.New()

  app.Use(sess.Handler())
  app.Use(func(ctx iris.Context){
    // session will expire after 30 minute at the last visit
    sess.UpdateExpiration(ctx, 30 * time.Minute)
    ctx.Next()
  })

  app.Get("/set", func(ctx iris.Context) {
    sessions.Get(ctx).Set("hello", "world")
    ctx.StatusCode(200)
  })

  app.Get("/get", func(ctx iris.Context) {
    ctx.WriteString(sessions.Get(ctx).GetString("hello"))
  })

  exit := m.Run()
  os.Exit(exit)
}

func TestSessionTimer(t *testing.T){
  e := httptest.New(t, app, httptest.URL("http://example.com"))

  e.GET("/set").Expect().Status(httptest.StatusOK)
  i := 0
  wg := sync.WaitGroup{}
  wg.Add(100)
  for i < 100 {
    go func() {
      tt := e.GET("/get").Expect().Status(httptest.StatusOK)
      tt.Body().Equal("world")
      tt.Cookie(cookieName).MaxAge().Equal(30 * time.Minute - time.Second)
      wg.Done()
    }()
    i++
  }
  wg.Wait()
  tt := e.GET("/get").Expect()
  tt.Status(httptest.StatusOK).Body().Equal("world")
  tt.Cookie(cookieName).MaxAge().Equal(30 * time.Minute - time.Second)
}

```

**Comment by huyinghuan** [comment]
Could it be a bug?

**Comment by kataras** [comment]
Hello @huyinghuan,

It passes here, indeed I run the test with `-count=100` and not only 100 concurrent requests per client but `1000` and it never panics. Tested on `go1.14.2 windows/amd64`.

```go
func TestSessionsUpdateExpirationConcurrently(t *testing.T) {
	cookieName := "mycustomsessionid"
	sess := sessions.New(sessions.Config{
		Cookie:       cookieName,
		Expires:      30 * time.Minute,
		AllowReclaim: true,
	})

	app := iris.New()
	app.Use(sess.Handler())
	app.Use(func(ctx iris.Context) {
		// session will expire after 30 minute at the last visit
		sess.UpdateExpiration(ctx, 30*time.Minute)
		ctx.Next()
	})

	app.Get("/get", func(ctx iris.Context) {
		ctx.WriteString(sessions.Get(ctx).ID())
	})

	e := httptest.New(t, app, httptest.URL("http://example.com"))

	id := e.GET("/get").Expect().Status(httptest.StatusOK).Body().Raw()

	i := 0
	wg := sync.WaitGroup{}
	wg.Add(1000)
	for i < 1000 {
		go func() {
			tt := e.GET("/get").Expect().Status(httptest.StatusOK)
			tt.Body().Equal(id)
			tt.Cookie(cookieName).MaxAge().InRange(29*time.Minute, 30*time.Minute)
			wg.Done()
		}()
		i++
	}
	wg.Wait()
	tt := e.GET("/get").Expect()
	tt.Status(httptest.StatusOK).Body().Equal(id)
	tt.Cookie(cookieName).MaxAge().InRange(29*time.Minute, 30*time.Minute)
}
```

```sh
PS C:\mygopath\src\github.com\kataras\iris\sessions> go version
go version go1.14.2 windows/amd64
PS C:\mygopath\src\github.com\kataras\iris\sessions> go test -v -count=100 -run=TestSessionsUpdateExpirationConcurrently$
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.01s)
=== RUN   TestSessionsUpdateExpirationConcurrently        
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently        
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently        
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently        
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.01s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.01s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.01s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
=== RUN   TestSessionsUpdateExpirationConcurrently
--- PASS: TestSessionsUpdateExpirationConcurrently (0.00s)
PASS
ok      github.com/kataras/iris/v12/sessions    0.969s
```

However, if you still have issues we must find a solution, are you sure that this is a real-world problem?
