### ISSUE TITLE
[BUG] MVC:  expected [3] bindings (input parameters) but got [2]

### ISSUE THREAD

**Issue by Dexus** [kataras/iris#1542]
**Describe the bug**
If you set one param to MVC function it works, but when you set 2 params to function it panics

as you mentions in https://github.com/kataras/iris/issues/1541#issuecomment-646731476

I have a `func (cpc *CategoryPrivateController) PostByProducts(categoryID uint64) {` that works but if i use `func (cpc *CategoryPrivateController) PostByProducts(categoryID uint64, products models.ProductSlice) {` is prints `expected [3] bindings (input parameters) but got [2]`

**To Reproduce**
```
// CategoryPrivateController serves the "public-private" Category API.
type CategoryPrivateController struct {
	BaseController // Ctx , Session ...
}

// PostByProducts desc
// Route /category/{id:uint64}/products [POST]
func (cpc *CategoryPrivateController) PostByProducts(categoryID uint64, products models.ProductSlice) {
...
}
```

**Expected behavior**
Accept my 2 parameters and don't expected 3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, windows]

**Additional context**
as always master branch

EDIT:
products models.ProductSlice should be the posted JSON data

current workaround to call this in the func
```

var products models.ProductSlice
	cpc.Ctx.ReadJSON(&products)
````

**Comment by kataras** [comment]
@Dexus strange, something like that works here:

```go
func (*testControllerMethodHandlerBindStruct) PostByProducts(id uint64, data queryData) queryData {
	return data
}

// [...]
e := httptest.New(t, app)
e.POST("/42/products").WithJSON(data).Expect().Status(httptest.StatusOK).JSON().Equal(data)
```

**Comment by kataras** [comment]
@Dexus strange, something like that works here:

```go
func (*testControllerMethodHandlerBindStruct) PostByProducts(id uint64, data queryData) queryData {
	return data
}
```
```go
New(app.Party("/data")).Handle(new(testControllerMethodHandlerBindStruct))
```
```go
e := httptest.New(t, app)
e.POST("/data/42/products").WithJSON(data).Expect().Status(httptest.StatusOK).JSON().Equal(data)
```

**Comment by kataras** [comment]
There is an issue when accept list though, it doesn't panic with unexpected inputs, but I got the error message of: `controller_test.go:731: Path: /data/42/products, Error: json: cannot unmarshal array 
into Go value of type mvc_test.bindStructData`

```go
m.HandleError(func(ctx iris.Context, err error) {
	t.Fatalf("Path: %s, Error: %v", ctx.Path(), err)
})
```

Let me investigate it.

**Comment by Dexus** [comment]
I uses [sqlboiler ](https://github.com/volatiletech/sqlboiler) and from the SQL generated models.

After register each Slice of Models, it works. 

```
type (
	// CustomerSlice is an alias for a slice of pointers to Customer.
	// This should generally be used opposed to []Customer.
	CustomerSlice []*Customer
)

api.RegisterDependency(func(ctx iris.Context) (v models.CustomerSlice, err error) {
		err = ctx.ReadJSON(&v)
		return
	})
```

it was interesting that this not work without register, because `myLimit MyLimiter` works without register out of the box.

**Comment by Dexus** [comment]
If you like to the the full Panic error with out register the slice:

```
panic: expected [3] bindings (input parameters) but got [2]

goroutine 1 [running]:
github.com/kataras/iris/v12/hero.getBindingsForFunc(0xc000251ec0, 0xc0002ac5c8, 0x13, 0xc000251800, 0xb, 0xc, 0x1, 0xc000483778, 0x7f4c6a9c9273, 0xc0002ee360)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/hero/binding.go:236 +0x2ce
github.com/kataras/iris/v12/hero.makeHandler(0x7f4c6b7a7ba0, 0xc0002ee360, 0xc0001f4e80, 0x1, 0xe)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/hero/handler.go:81 +0x158
github.com/kataras/iris/v12/hero.(*Struct).MethodHandler(0xc000251740, 0x7f4c6b5d0b86, 0xe, 0x1, 0xf)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/hero/struct.go:151 +0x107
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handlerOf(0xc000251680, 0xc000038f80, 0x19, 0x7f4c6b5d0b86, 0xe, 0x4)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:384 +0x16d
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handleMany(0xc000251680, 0x7f4c6b29f3d1, 0x4, 0xc000038f80, 0x19, 0x7f4c6b5d0b86, 0xe, 0xc000251e00, 0x0, 0x0, ...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:345 +0x97
github.com/kataras/iris/v12/mvc.(*ControllerActivator).Handle(...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:314
github.com/kataras/iris/v12/mvc.(*ControllerActivator).parseMethod(0xc000251680, 0x7f4c6b5d0b86, 0xe, 0x0, 0x0, 0x7f4c6b7ea2e0, 0xc000251ec0, 0xc000251ec0, 0xc0002ac5b0, 0x13, ...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:297 +0x2a9
github.com/kataras/iris/v12/mvc.(*ControllerActivator).parseMethods(0xc000251680)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:283 +0xd1
github.com/kataras/iris/v12/mvc.(*ControllerActivator).activate(...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:275
github.com/kataras/iris/v12/mvc.(*Application).handle(0xc0002515c0, 0x7f4c6b736440, 0xc0001f4d00, 0x0, 0x0, 0x0, 0x7f4c6b7ea880)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/mvc.go:264 +0x1ef
github.com/kataras/iris/v12/mvc.(*Application).Handle(...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/mvc.go:206
myecomapp/api.RegisterRoutes(0xc0000f8d10, 0xc0002ac020)
        /mnt/w/projects/iris_certificate/ecom/api/api.go:81 +0x43a
main.newApp(0x0)
        /mnt/w/projects/iris_certificate/ecom/main.go:40 +0x459
main.main()
        /mnt/w/projects/iris_certificate/ecom/main.go:17 +0x28
exit status 2
exited: exit status 1
>> restart backoff... 8000ms
>> starting...
panic: expected [3] bindings (input parameters) but got [2]

goroutine 1 [running]:
github.com/kataras/iris/v12/hero.getBindingsForFunc(0xc0002d6540, 0xc0002205c0, 0x13, 0xc000457e60, 0xb, 0xc, 0x1, 0xc0004a9778, 0x7f095f5d6273, 0xc0002d8380)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/hero/binding.go:236 +0x2ce
github.com/kataras/iris/v12/hero.makeHandler(0x7f09603b4ba0, 0xc0002d8380, 0xc0001c4e80, 0x1, 0xe)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/hero/handler.go:81 +0x158
github.com/kataras/iris/v12/hero.(*Struct).MethodHandler(0xc000457da0, 0x7f09601ddb86, 0xe, 0x1, 0xf)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/hero/struct.go:151 +0x107
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handlerOf(0xc000457ce0, 0xc000298e00, 0x19, 0x7f09601ddb86, 0xe, 0x4)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:384 +0x16d
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handleMany(0xc000457ce0, 0x7f095feac3d1, 0x4, 0xc000298e00, 0x19, 0x7f09601ddb86, 0xe, 0xc0002d6500, 0x0, 0x0, ...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:345 +0x97
github.com/kataras/iris/v12/mvc.(*ControllerActivator).Handle(...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:314
github.com/kataras/iris/v12/mvc.(*ControllerActivator).parseMethod(0xc000457ce0, 0x7f09601ddb86, 0xe, 0x0, 0x0, 0x7f09603f72e0, 0xc0002d6540, 0xc0002d6540, 0xc0002205a8, 0x13, ...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:297 +0x2a9
github.com/kataras/iris/v12/mvc.(*ControllerActivator).parseMethods(0xc000457ce0)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:283 +0xd1
github.com/kataras/iris/v12/mvc.(*ControllerActivator).activate(...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/controller.go:275
github.com/kataras/iris/v12/mvc.(*Application).handle(0xc000457c20, 0x7f0960343440, 0xc0001c4d00, 0x0, 0x0, 0x0, 0x7f09603f7880)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/mvc.go:264 +0x1ef
github.com/kataras/iris/v12/mvc.(*Application).Handle(...)
        /home/josef/go/pkg/mod/github.com/kataras/iris/v12@v12.1.9-0.20200619025421-80384f32b25a/mvc/mvc.go:206
myecomapp/api.RegisterRoutes(0xc0000e2c60, 0xc000220018)
        /mnt/w/projects/iris_certificate/ecom/api/api.go:81 +0x43a
main.newApp(0x0)
        /mnt/w/projects/iris_certificate/ecom/main.go:40 +0x459
main.main()
        /mnt/w/projects/iris_certificate/ecom/main.go:17 +0x28
exit status 2
exited: exit status 1
```

**Comment by kataras** [comment]
> I uses [sqlboiler ](https://github.com/volatiletech/sqlboiler) and from the SQL generated models.
> 
> After register each Slice of Models, it works.
> 
> ```
> type (
> 	// CustomerSlice is an alias for a slice of pointers to Customer.
> 	// This should generally be used opposed to []Customer.
> 	CustomerSlice []*Customer
> )
> 
> api.RegisterDependency(func(ctx iris.Context) (v models.CustomerSlice, err error) {
> 		err = ctx.ReadJSON(&v)
> 		return
> 	})
> ```
> 
> it was interesting that this not work without register, because `myLimit MyLimiter` works without register out of the box.

Yes because this is not a struct or go std type or slice. Its a custom type of slice so the automatic binding is not registered at all, and the panic msg is the correct one (the controller's method receiver, the path parameter and the custom type)

**Comment by Dexus** [comment]
Okay, I get it. Now I know again why I didn't use the MVC so often before ^^ 

Okay, but now what I'm about to do is working. In the future I think there will be some projects updated, even if that means many many many many registrations of different structures and types.

**Comment by kataras** [comment]
No @Dexus only custom types that are slices are required to `Register`, otherwise automatic binding will work.

**Comment by kataras** [comment]
@Dexus  I updated my answer above, the issue is that it's a custom slice  type **of pointers**, if you change it to `CustomerSlice []Customer`  it **will work**, otherwise register that `CustomerSlice` (and others custom slices of pointers) for now, I am working to "fix" it.

**Comment by Dexus** [comment]
Okay, thank you.

**Comment by kataras** [comment]
Fixed.

**Comment by Dexus** [comment]
Thank you very much @kataras

**Comment by kataras** [comment]
It was an easy fix @Dexus, thank YOU for the bug report!
