### ISSUE TITLE
examples/websocket is broken (win7 64 go1.6)

### ISSUE THREAD

**Issue by max107** [kataras/iris#161]
```bash
$ cat main.go
package main

import (
	"fmt"

	"github.com/kataras/iris"
	"github.com/kataras/iris/websocket"
)

type clientPage struct {
	Title string
	Host  string
}

func main() {
	iris.Static("/js", "./static/js", 1)

	iris.Get("/", func(ctx *iris.Context) {
		ctx.Render("client.html", clientPage{"Client Page", ctx.HostString()})
	})

	// the path which the websocket client should listen/registed to ->
	iris.Config().Websocket.Endpoint = "/my_endpoint"
	// for Allow origin you can make use of the middleware
	//iris.Config().Websocket.Headers["Access-Control-Allow-Origin"] = "*"

	ws := iris.Websocket() // get the websocket server

	var myChatRoom = "room1"
	ws.OnConnection(func(c websocket.Connection) {

		c.Join(myChatRoom)

		c.On("chat", func(message string) {
			// to all except this connection ->
			//c.To(websocket.Broadcast).Emit("chat", "Message from: "+c.ID()+"-> "+message)

			// to the client ->
			//c.Emit("chat", "Message from myself: "+message)

			//send the message to the whole room,
			//all connections are inside this room will receive this message
			c.To(myChatRoom).Emit("chat", "From: "+c.ID()+": "+message)
		})

		c.OnDisconnect(func() {
			fmt.Printf("\nConnection with ID: %s has been disconnected!", c.ID())
		})
	})

	iris.Listen(":8080")
}
$ go get -v .
	github.com/kataras/iris (download)
	github.com/fatih/color (download)
	github.com/imdario/mergo (download)
	github.com/microcosm-cc/bluemonday (download)
	github.com/russross/blackfriday (download)
	github.com/shurcooL/sanitized_anchor_name (download)
	github.com/eknkc/amber (download)
	github.com/Joker/jade (download)
	github.com/garyburd/redigo (download)
	github.com/iris-contrib/websocket (download)
	go install: no install location for directory D:\projects\demo outside GOPATH
		For more details see: go help gopath
	
	exit status 1
$ go get -u github.com/valyala/fasthttp
$ go build
$ ./demo.exe
                        _____      _
                       |_   _|    (_)
                         | |  ____ _  ___
                         | | | __|| |/ __|
                        _| |_| |  | |\__ \
                       |_____|_|  |_||___/


Mon, 30 May 2016 21:21:03 GMT: Running at :8080

Connection with ID: FADQZCqgQsrQhukhjbsryoJwcVZaKSuovSahdhoUGaYwcodxMhNDSnjNfFHlwIRM has been disconnected!2016/05/30 21:21:15 panic on hijacked conn: interface conversion: interface is int, not string
Stack trace:
goroutine 19 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        C:/Go/src/runtime/debug/stack.go:24 +0x87
github.com/valyala/fasthttp.hijackConnHandler.func1(0x14c0060, 0xc0820262a8, 0xc0821c5cc0, 0x14c0000, 0xc0820262a8, 0xc08221e620)
        c:/GoSrc/src/github.com/valyala/fasthttp/server.go:1626 +0x84
panic(0xa87300, 0xc082210540)
        C:/Go/src/runtime/panic.go:426 +0x4f7
github.com/kataras/iris/websocket.(*connection).messageReceived(0xc082384000, 0xc08238a000, 0x1f, 0x600)
        c:/GoSrc/src/github.com/kataras/iris/websocket/connection.go:159 +0x316
github.com/kataras/iris/websocket.(*connection).reader(0xc082384000)
        c:/GoSrc/src/github.com/kataras/iris/websocket/connection.go:133 +0x2c7
github.com/kataras/iris/websocket.(*server).handleConnection(0xc082144e70, 0xc08236e240)
        c:/GoSrc/src/github.com/kataras/iris/websocket/server.go:87 +0x9d
github.com/kataras/iris/websocket.(*server).(github.com/kataras/iris/websocket.handleConnection)-fm(0xc08236e240)
        c:/GoSrc/src/github.com/kataras/iris/websocket/server.go:73 +0x31
github.com/iris-contrib/websocket.(*Upgrader).Upgrade.func1(0x14c0170, 0xc08221e620)
        c:/GoSrc/src/github.com/iris-contrib/websocket/server.go:309 +0xc6
github.com/valyala/fasthttp.hijackConnHandler(0x14c0060, 0xc0820262a8, 0x14c0000, 0xc0820262a8, 0xc0821c5cc0, 0xc0822201b0)
        c:/GoSrc/src/github.com/valyala/fasthttp/server.go:1636 +0xfb
created by github.com/valyala/fasthttp.(*Server).serveConn
        c:/GoSrc/src/github.com/valyala/fasthttp/server.go:1549 +0xee5
```

**Comment by kataras** [comment]
@max107  Are you sure? I just run it, make `go get -u github.com/kataras/iris`and tell me again or provide me more informations

**Comment by max107** [comment]
see above

**Comment by max107** [comment]
@kataras

Mac, El capitan.

```bash
                        _____      _
                       |_   _|    (_)
                         | |  ____ _  ___
                         | | | __|| |/ __|
                        _| |_| |  | |\__ \
                       |_____|_|  |_||___/


Tue, 31 May 2016 09:16:07 GMT: Running at :8080
2016/05/31 09:16:11 panic on hijacked conn: interface conversion: interface is int, not string
Stack trace:
goroutine 42 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/debug/stack.go:24 +0x80
github.com/valyala/fasthttp.hijackConnHandler.func1(0xf8cab8, 0xc8202580b0, 0xc82027a000, 0xf8ca58, 0xc8202580b0, 0xc82025dac0)
	/Volumes/mac/max/.go/src/github.com/valyala/fasthttp/server.go:1626 +0x7d
panic(0x673ba0, 0xc8202549c0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x4e9
github.com/kataras/iris/websocket.(*connection).messageReceived(0xc82038c000, 0xc82038e000, 0x1f, 0x600)
	/Volumes/mac/max/.go/src/github.com/kataras/iris/websocket/connection.go:159 +0x30f
github.com/kataras/iris/websocket.(*connection).reader(0xc82038c000)
	/Volumes/mac/max/.go/src/github.com/kataras/iris/websocket/connection.go:133 +0x2c0
github.com/kataras/iris/websocket.(*server).handleConnection(0xc8202660b0, 0xc82027e5a0)
	/Volumes/mac/max/.go/src/github.com/kataras/iris/websocket/server.go:87 +0x96
github.com/kataras/iris/websocket.(*server).(github.com/kataras/iris/websocket.handleConnection)-fm(0xc82027e5a0)
	/Volumes/mac/max/.go/src/github.com/kataras/iris/websocket/server.go:73 +0x2a
github.com/iris-contrib/websocket.(*Upgrader).Upgrade.func1(0xfc13c8, 0xc82025dac0)
	/Volumes/mac/max/.go/src/github.com/iris-contrib/websocket/server.go:309 +0xbf
github.com/valyala/fasthttp.hijackConnHandler(0xf8cab8, 0xc8202580b0, 0xf8ca58, 0xc8202580b0, 0xc82027a000, 0xc820252a50)
	/Volumes/mac/max/.go/src/github.com/valyala/fasthttp/server.go:1636 +0xf4
created by github.com/valyala/fasthttp.(*Server).serveConn
	/Volumes/mac/max/.go/src/github.com/valyala/fasthttp/server.go:1549 +0xede

Connection with ID: IwyuvFdDlPxjzPMcUNrmqhJJIvtEwdCoVbCYtVbKOLPvvudZmsLZdOzLjsBcTSAY has been disconnected!panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x150055]

goroutine 43 [running]:
panic(0x66ec00, 0xc82000a0c0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0xc82025dac0, 0xecedf2335, 0xc80267515f, 0xac4ba0, 0x0, 0x0)
	<autogenerated>:35 +0x75
github.com/iris-contrib/websocket.(*Conn).write(0xc82027e5a0, 0x8, 0xecedf2335, 0x267515f, 0xac4ba0, 0xc820295cc0, 0x2, 0x2, 0x0, 0x0)
	/Volumes/mac/max/.go/src/github.com/iris-contrib/websocket/conn.go:293 +0x12c
github.com/iris-contrib/websocket.(*Conn).flushFrame(0xc82027e5a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Volumes/mac/max/.go/src/github.com/iris-contrib/websocket/conn.go:455 +0x713
github.com/iris-contrib/websocket.(*Conn).WriteMessage(0xc82027e5a0, 0x8, 0xae2448, 0x0, 0x0, 0x0, 0x0)
	/Volumes/mac/max/.go/src/github.com/iris-contrib/websocket/conn.go:595 +0x18c
github.com/kataras/iris/websocket.(*connection).write(0xc82038c000, 0x8, 0xae2448, 0x0, 0x0, 0x0, 0x0)
	/Volumes/mac/max/.go/src/github.com/kataras/iris/websocket/connection.go:82 +0x1aa
github.com/kataras/iris/websocket.(*connection).writer(0xc82038c000)
	/Volumes/mac/max/.go/src/github.com/kataras/iris/websocket/connection.go:96 +0x1b7
created by github.com/kataras/iris/websocket.(*server).handleConnection
	/Volumes/mac/max/.go/src/github.com/kataras/iris/websocket/server.go:86 +0x88
```

websocket example is broken

**Comment by kataras** [comment]
Both of the websocket examples were tested on linux, windows and mac OS via vmware. 

Please provide me with more information, when this error happen? on Join room? or sending Message? what type of message?

**Comment by max107** [comment]
> sending Message

**Comment by kataras** [comment]
What browser? ( tested with google chrome and firefox)

**Comment by kataras** [comment]
@max107  Upgrade iris with ` go get -u github.com/kataras/iris/iris` , the problem is fixed, thanks you and sorry for the invalid label!

**Comment by max107** [comment]
@kataras thx!
