### ISSUE TITLE
v3.0.0-beta.1 Config Panic

### ISSUE THREAD

**Issue by ryanbyyc** [kataras/iris#167]
```language:go
func main() {
    cfg := config.Iris{Profile: true, DisablePathCorrection: true}
    api := iris.New(cfg)
    api.Listen(":8080")
}
```

```
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x561c20, 0xc820209790)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/kataras/iris.(*Iris).initTemplates(0xc82021e400)
    /Users/ryan/Go/src/github.com/kataras/iris/iris.go:140 +0x2ca
github.com/kataras/iris.(*Iris).PostListen(0xc82021e400)
    /Users/ryan/Go/src/github.com/kataras/iris/iris.go:243 +0x10b
github.com/kataras/iris.(*Iris).listen(0xc82021e400, 0x74d958, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc800000000, 0x0, 0x0)
    /Users/ryan/Go/src/github.com/kataras/iris/iris.go:264 +0xc3
github.com/kataras/iris.(*Iris).ListenWithErr(0xc82021e400, 0x74d958, 0x5, 0x0, 0x0)
    /Users/ryan/Go/src/github.com/kataras/iris/iris.go:282 +0x9b
github.com/kataras/iris.(*Iris).Listen(0xc82021e400, 0x74d958, 0x5)
    /Users/ryan/Go/src/github.com/kataras/iris/iris.go:292 +0x35
main.main()
    /app/web/main.go:12 +0xfe
exit status 2
```

Eventually I traced it down to an issue with DefaultConfigs.
```language:go
	cfg.Render.Template.HTMLTemplate = config.HTMLTemplate{
// ...
	}
```

Now I can get around this with something like:
```go
	cfg.Render.Template.HTMLTemplate.Left = "{{"
	// ...
```

But I shouldn't need to.

**Comment by kataras** [comment]
Yes, it should do it automatically with Merge, as it was, I'm looking into this right now

**Comment by kataras** [comment]
@ryanbyyc  fixed
