### ISSUE TITLE
[BUG] (ctx *Context) PostValueInt64(name string) index out of range

### ISSUE THREAD

**Issue by jonsen** [kataras/iris#1681]
**Describe the bug**

when POST empty values, panic happend.

panic massge:
```
[HTTP Server] http: panic serving 127.0.0.1:60385: runtime error: index out of range [-1]
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc0005b4140)
	/usr/local/opt/go/libexec/src/net/http/server.go:1801 +0x147
panic(0x1b876c0, 0xc000436ca0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:975 +0x47a
github.com/kataras/iris/v12/context.(*Context).PostValueInt64(0xc0005b4280, 0x1c08bd5, 0x4, 0xffffffffffffffff, 0x1dcfaa0, 0xc00041eaa0)
	/opt/workspace/gopkg/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201117050536-962ffd67721a/context/context.go:1867 +0xde
```

context.go code:
```
// PostValueInt64 returns the last parsed form data from POST, PATCH,
// or PUT body parameters based on a "name", as float64.
//
// See ErrEmptyForm, ErrNotFound and ErrEmptyFormField respectfully.
func (ctx *Context) PostValueInt64(name string) (int64, error) {
	values, err := ctx.PostValues(name)
	if err != nil {
		return -1, err
	}

	return strconv.ParseInt(values[len(values)-1], 10, 64)
}
```

**To Reproduce**
1. [...]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, windows]

**iris.Version**
- e.g. v12.2.0-alpha or master

Please make sure the bug is reproducible over the `master` branch:

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**Additional context**

**Comment by kataras** [comment]
You are right @jonsen, I am going to fix it rn. However, this could be solved by enabling the [FireEmptyFormError](https://github.com/kataras/iris/blob/962ffd67721ab7612702c7a48db645f6226977e4/configuration.go#L722) also.
