### ISSUE TITLE
[BUG] `Strict: false` in gRPC Configs causes a Panic

### ISSUE THREAD

**Issue by ajohnson-veri** [kataras/iris#1819]
**Describe the bug**
I am setting up a gRPC server using Iris and trying to disable the need for using authentication/TLS - (i.e. Allow my server to accept `http://` requests in addition to `https://`).

In order for the gRPC server to accept http connections the `mvc.GRPC` configuration needs to have the `Strict` option set to false. The Strict options description is - "When Strict option is true then this controller will only serve gRPC-based clients and fires 404 on common HTTP clients."

When I use the following configuration...

```
mvc.GRPC{
	Server:      grpcServer,             
	ServiceName: string(grpcServiceName),
	Strict:      false,
}
```

...I get the following panic / error on server startup....

```
panic: reflect: call of reflect.Value.NumField on ptr Value

goroutine 1 [running]:
reflect.flag.mustBe(...)
	/usr/local/go/src/reflect/value.go:221
reflect.Value.NumField(0x118ff00, 0xc0005c0330, 0x196, 0x140f590)
	/usr/local/go/src/reflect/value.go:1369 +0xc5
github.com/kataras/iris/v12/hero.lookupFields(0x118ff00, 0xc0005c0330, 0x196, 0x1, 0xc0005be808, 0x1, 0x1, 0x1, 0x30, 0xc0005be800, ...)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/hero/reflect.go:124 +0xa5
github.com/kataras/iris/v12/hero.lookupFields(0x119aa00, 0xc0005c0300, 0x199, 0x1000001, 0x0, 0x0, 0x0, 0x1, 0x2f, 0x0, ...)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/hero/reflect.go:133 +0x616
github.com/kataras/iris/v12/hero.lookupNonZeroFieldValues(0x119aa00, 0xc0005c0300, 0x199, 0x119aa00, 0xc0005c0300, 0x199)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/hero/reflect.go:165 +0x75
github.com/kataras/iris/v12/hero.getBindingsForStruct(0x1194da0, 0xc0005c0300, 0x16, 0xc000416600, 0xd, 0x18, 0x0, 0x0, 0x1228f78, 0x0, ...)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/hero/binding.go:289 +0x105
github.com/kataras/iris/v12/hero.makeStruct(0x11a2340, 0xc00000e228, 0xc0009923f0, 0x0, 0x10)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/hero/struct.go:54 +0x17e
github.com/kataras/iris/v12/hero.(*Container).Struct(...)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/hero/container.go:352
github.com/kataras/iris/v12/mvc.(*ControllerActivator).attachInjector(0xc0009924d0)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/mvc/controller.go:285 +0x1bd
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handlerOf(0xc0009924d0, 0xc000444360, 0x29, 0xf7ba77, 0x9, 0xc000444360)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/mvc/controller.go:445 +0x45
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handleMany(0xc0009924d0, 0x11a8793, 0x4, 0xc000444360, 0x29, 0xf7ba77, 0x9, 0xc000548400, 0xc0002b28e8, 0x1, ...)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/mvc/controller.go:403 +0xfb
github.com/kataras/iris/v12/mvc.(*ControllerActivator).Handle(...)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/mvc/controller.go:347
github.com/kataras/iris/v12/mvc.GRPC.Apply(0x13e9940, 0xc000406700, 0xc000418bb0, 0x1f, 0x0, 0xc0009924d0)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/mvc/grpc.go:59 +0x34e
github.com/kataras/iris/v12/mvc.(*Application).handle(0xc000992460, 0x1194da0, 0xc0005c0300, 0xc000575ba0, 0x1, 0x1, 0xc00098b650)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/mvc/mvc.go:306 +0x205
github.com/kataras/iris/v12/mvc.(*Application).Handle(0xc000992460, 0x1194da0, 0xc0005c0300, 0xc000575ba0, 0x1, 0x1, 0x1)
	/processors/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha2.0.20210914191044-a9b97e005ab6/mvc/mvc.go:246 +0x65
main.configureVoice(0xc0005c0300, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/myApplication/server.go:42 +0x3d5
main.main()
	/myApplication/server.go:73 +0x245
make: *** [local] Error 2
```

...And the stack trace from my own code at `/myApplication/server.go:42` is ...

```
pb.RegisterMyServer(grpcServer, myServer)
mvc.New(myApplication).Handle(myServer, mvc.GRPC{
	Server:      grpcServer,              // Required
	ServiceName: string(grpcServiceName), // Required
	Strict:      false,
})
```

In the above code snippet `myServer` is a pointer to a struct.

**To Reproduce**

Take one of the generic Iris web app / grpc server examples and attempt to set the `Strict` option in the grpc config to false.
Code snippets are provided in the description above for more detail on how this issue was reached.

**Expected behavior**

**Desktop (please complete the following information):**
 - (Built On) OS: mac OS Catalina 10.15.7
 - (Run On) OS: Docker Image `nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04`- https://hub.docker.com/r/nvidia/cuda

**iris.Version**
- v12.2.0-alpha2 - latest release as of making this issue

Please make sure the bug is reproducible over the `master` branch: [done]

```sh
$ cd PROJECT
$ go get -u github.com/kataras/iris/v12@master
$ go run .
```

**This bug is reproducible on master**

**Screen Shots**
N/A

**Additional context**
For reference, not that I would have expected the following hack/workaround to actually resolve the issue, but attempting to dereference the server before passing it to `.Handle(...)` results in the following error.

Code:
```
mvc.New(myApplication).Handle(*myServer, mvc.GRPC{
	Server:      grpcServer,              // Required
	ServiceName: string(grpcServiceName), // Required
	Strict:      false,
})
```

Error:  `panic: binder: struct: should be a pointer to a struct value`

**Comment by kataras** [comment]
Hello @ajohnson-veri,

I am trying to reproduce the issue and I cannot. Following the https://github.com/kataras/iris/tree/master/_examples/mvc/grpc-compatible example. Could you please provide us a complete example and steps to reproduce the above issue?

**Comment by ajohnson-veri** [comment]
I also wasn't able to reproduce it from the example in its starting state. I will start incorporating configuration changes from my own project to see if I can root cause which specific change is causing this behavior.

**Comment by kataras** [comment]
@ajohnson-veri do we have any news regarding this or should I mark it as false report? Thanks!
