### ISSUE TITLE
The line may have a bug?

### ISSUE THREAD

**Issue by insionng** [kataras/iris#20]
```
package main

import "github.com/kataras/iris"

func main() {

    //log everything middleware

    iris.UseFunc(func(c *iris.Context) {
        println("[Global log] the requested url path is: ", c.Request.URL.Path)
        c.Next()
    })

    // Party inside an existing Party example:

    beta:= iris.Party("/beta")

    admin := beta.Party("/admin")
    {
        /// GET: /beta/admin/
        admin.Get("/", func(c *iris.Context){})
        /// POST: /beta/admin/signin
        admin.Post("/signin", func(c *iris.Context){})
        /// GET: /beta/admin/dashboard
        admin.Get("/dashboard", func(c *iris.Context){})
        /// PUT: /beta/admin/users/add
        admin.Put("/users/add", func(c *iris.Context){})
    }



    iris.Listen(":8080")
}
```

```
    admin := beta.Party("/admin")
```

errors:
```
go build app.go && ./app
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x78 pc=0x475937]

goroutine 1 [running]:
panic(0x809ec0, 0xc82000a180)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/kataras/iris.(*party).SetParentHosterMiddleware(0xc8200183c0, 0x0, 0x0, 0x0)
	<autogenerated>:165 +0x67
github.com/kataras/iris.party.Party(0x0, 0x0, 0x0, 0x0, 0x0, 0x7f3fdab89958, 0xc820090410, 0x0, 0x0, 0x0, ...)
	/mnt/Gopath/src/github.com/kataras/iris/party.go:133 +0xdb
github.com/kataras/iris.(*party).Party(0xc820018360, 0x88c490, 0x6, 0x0, 0x0)
	<autogenerated>:180 +0xce
main.main()
	/home/insion/Documents/yougam/app.go:40 +0x377
insion@idesktop:~/Documents/yougam$ go build app.go && ./app
^C
insion@idesktop:~/Documents/yougam$ go build app.go && ./app
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x78 pc=0x475477]

goroutine 1 [running]:
panic(0x808ec0, 0xc82000a180)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/kataras/iris.(*party).SetParentHosterMiddleware(0xc820148120, 0x0, 0x0, 0x0)
	<autogenerated>:165 +0x67
github.com/kataras/iris.party.Party(0x0, 0x0, 0x0, 0x0, 0x0, 0x7f22949b6418, 0xc82013a140, 0x0, 0x0, 0x0, ...)
	/mnt/Gopath/src/github.com/kataras/iris/party.go:133 +0xdb
github.com/kataras/iris.(*party).Party(0xc8201480c0, 0x88b490, 0x6, 0x0, 0x0)
	<autogenerated>:180 +0xce
main.main()
	/home/insion/Documents/app.go:18 +0xe4
```

**Comment by kataras** [comment]
@insionng  I made a lot of errors for extend the Iris to other middlewares too and I had to chgange a lot of things, I will look threw on it and I will fix it I just woke up thanks !

**Comment by kataras** [comment]
@insionng  OK Fixed

**Comment by insionng** [comment]
Thanks~

**Comment by kataras** [comment]
@insionng  you can define domains and subdomains to the Parties now ( new feature) , check _examples/ !

**Comment by insionng** [comment]
@kataras Very cool!
