### ISSUE TITLE
[BUG] fail running api_builder_benchmark_test.go

### ISSUE THREAD

**Issue by marek-kuticka** [kataras/iris#2147]
**Describe the bug**

GOROOT=/opt/homebrew/Cellar/go/1.20.4/libexec #gosetup
GOPATH=/Users/marek/go #gosetup
/opt/homebrew/Cellar/go/1.20.4/libexec/bin/go test -c -o /Users/marek/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___BenchmarkAPIBuilder_in_github_com_kataras_iris_v12_core_router.test github.com/kataras/iris/v12/core/router #gosetup
/Users/marek/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___BenchmarkAPIBuilder_in_github_com_kataras_iris_v12_core_router.test -test.v -test.paniconexit0 -test.bench ^\QBenchmarkAPIBuilder\E$ -test.run ^$
goos: darwin
goarch: arm64
pkg: github.com/kataras/iris/v12/core/router
BenchmarkAPIBuilder
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1051db214]

goroutine 6 [running]:
github.com/kataras/iris/v12/core/router.NewDefaultHandler({0x0, 0x0}, 0x0)
	/Users/marek/Downloads/iris-master/core/router/handler.go:69 +0x24
github.com/kataras/iris/v12/core/router.BenchmarkAPIBuilder(0x14000612000)
	/Users/marek/Downloads/iris-master/core/router/api_builder_benchmark_test.go:88 +0x114
testing.(*B).runN(0x14000612000, 0x1)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/benchmark.go:193 +0x12c
testing.(*B).run1.func1()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/benchmark.go:233 +0x50
created by testing.(*B).run1
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/benchmark.go:226 +0x90

Process finished with the exit code 2

**To Reproduce**
execute test from fresh build

**Comment by kataras** [comment]
Thanks @marek-kuticka, fixed!
