### ISSUE TITLE
[BUG] may be an out-of-boundary bug as a result of lack of necessary argument checks

### ISSUE THREAD

**Issue by secsys-go** [kataras/iris#2215]
**Describe the bug**
We used the Fuzz engine to modify some Test(TestUseRouterParentDisallow) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

**To Reproduce**
```go
app := iris.New()
app.PartyFunc("", func(p iris.Party) {})
```

**Crash Log**
```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 10 [running]:
testing.tRunner.func1.2({0xc4c5c0, 0xc00045a2a0})
	D:/.../go1.20/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	D:/.../go1.20/src/testing/testing.go:1529 +0x39f
panic({0xc4c5c0, 0xc00045a2a0})
	D:/.../go1.20/src/runtime/panic.go:884 +0x213
github.com/kataras/iris/v12/core/router.(*APIBuilder).Party(0xc0001210e0, {0x0, 0x0}, {0x0, 0x0, 0x0})
	D:/.../iris/core/router/api_builder.go:846 +0x8f1
github.com/kataras/iris/v12/core/router.(*APIBuilder).PartyFunc(0xc0312d6078?, {0x0?, 0xc000097f60?}, 0xd4ab18)
	D:/.../iris/core/router/api_builder.go:924 +0x2a
github.com/kataras/iris/v12/core/router_test.TestUseRouterParentDisallow_POC(0x0?)
	D:/.../iris/core/router/TestUseRouterParentDisallow_POC_test.go:25 +0x2c
testing.tRunner(0xc0004829c0, 0xd4ab20)
	D:/.../go1.20/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	D:/.../go1.20/src/testing/testing.go:1629 +0x3ea
```

**Expected behavior**
Crash should not happen.

**Desktop:**
 - OS: Windows 10

**iris.Version**
- commit [24ba4e8](https://github.com/kataras/iris/commit/24ba4e8933b9d58096a56e5c6f2de968f80eb602)

**Comment by kataras** [comment]
Hello @secsys-go, this was expected, I modified the code so if empty relative path is given is translated to "/" now. However, we don't use this empty path anywhere in our documentation or examples.
