### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by DevSpouk** [kataras/iris#331]
Are you serious man? Shared memory and can not be locked?

**wrk -d20s -t5 -c5 http://localhost:9000**

```go
package main

import (
	"github.com/kataras/iris"
	"fmt"
	"sync"
)

func main() {
	iris.UseFunc(TestMiddleFunc)
	iris.Use(&TestMiddle{})
	iris.Get("/", func(c *iris.Context) {
		c.Write("Path: %s\n", c.Path())
	})("root")
	iris.Config.IsDevelopment = true
	iris.Config.Gzip = true

	iris.Listen("localhost:9000")

}
//---------------------------------------------------------------------------
//  middleware example
//---------------------------------------------------------------------------
func TestMiddleFunc(c *iris.Context) {
	fmt.Printf("[middleware] [func]\n")
	c.Next()
}
type TestMiddle struct {
	sync.Mutex
}

func (m *TestMiddle) Serve (c* iris.Context){
	//m.Lock()
	c.Session().Set("data","dfgdfgdfg")
	//m.Unlock()
	fmt.Printf("[middlewarte] [struct]\n")
	c.Next()
}
```
We get a law-governed error
```log
[middleware] [func]
[middlewarte] [struct]
[middleware] [func]
[middlewarte] [struct]
[middlewarte] [struct]
[middlewarte] [struct]
[middleware] [func]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6ec241]

goroutine 82 [running]:
panic(0xbebda0, 0xc82000a140)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
container/list.(*List).PushBack(0xc820151bf0, 0xc7e620, 0xc820461440, 0xc820461440)
	/usr/local/go/src/container/list/list.go:139 +0x1c1
github.com/kataras/iris.(*sessionProvider).init(0xc820175b00, 0xc82040b950, 0x2c, 0x0)
	/home/spouk/go/src/github.com/kataras/iris/sessions.go:191 +0x70
github.com/kataras/iris.(*sessionsManager).start(0xc82020dcc0, 0xc820018190, 0xc8202d4000)
	/home/spouk/go/src/github.com/kataras/iris/sessions.go:305 +0xbf
github.com/kataras/iris.(*Context).Session(0xc820018190, 0x0, 0x0)
	/home/spouk/go/src/github.com/kataras/iris/context.go:935 +0x69
main.(*TestMiddle).Serve(0xc82020dc88, 0xc820018190)
	/home/spouk/go/src/simple/iris_framework/server_bug_post.go:34 +0x25
github.com/kataras/iris.(*Context).Next(0xc820018190)
	/home/spouk/go/src/github.com/kataras/iris/context.go:157 +0x80
main.TestMiddleFunc(0xc820018190)
	/home/spouk/go/src/simple/iris_framework/server_bug_post.go:26 +0x4b
github.com/kataras/iris.HandlerFunc.Serve(0xe3ce58, 0xc820018190)
	/home/spouk/go/src/github.com/kataras/iris/http.go:616 +0x26
github.com/kataras/iris.(*Context).Do(0xc820018190)
	/home/spouk/go/src/github.com/kataras/iris/context.go:147 +0x5d
github.com/kataras/iris.(*serveMux).ServeRequest.func5(0xc8202d0480)
	/home/spouk/go/src/github.com/kataras/iris/http.go:1556 +0x472
github.com/valyala/fasthttp.(*Server).serveConn(0xc820210dc0, 0x8011678e0, 0xc82002a408, 0x0, 0x0)
	/home/spouk/go/src/github.com/valyala/fasthttp/server.go:1514 +0x973
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x8011678e0, 0xc82002a408, 0x0, 0x0)
	/home/spouk/go/src/github.com/valyala/fasthttp/server.go:1233 +0x42
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc820235600, 0xc820296640)
	/home/spouk/go/src/github.com/valyala/fasthttp/workerpool.go:210 +0x126
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc820235600, 0xc820296640, 0xa73f00, 0xc820296640)
	/home/spouk/go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x2b
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/spouk/go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x1e9
exit status 2
```

You can put a lock on the objects used by the shared memory?

```go 
func (m *TestMiddle) Serve (c* iris.Context){
	m.Lock()
	c.Session().Set("data","dfgdfgdfg")
	m.Unlock()
	fmt.Printf("[middlewarte] [struct]\n")
	c.Next()
}
```

**Comment by kataras** [comment]
Man you have to upgrade the framework, you have a very old version of it
- Remove $GOPATH/src/github.com/kataras 
- execute: `go get -u github.com/kataras/iris/iris`
