### ISSUE TITLE
panic: template: help_message:10: illegal number syntax: "-"

### ISSUE THREAD

**Issue by pavelz** [kataras/iris#378]
after compiling "Hi" I get this error message:

```
goroutine 1 [running]:
github.com/kataras/iris.init.2()
        /home/pavel/projects/learn.iris/src/github.com/kataras/iris/ssh.go:249 +0x394
github.com/kataras/iris.init()
        /home/pavel/projects/learn.iris/src/github.com/kataras/iris/websocket.go:957 +0xa5e
main.init()
        /home/pavel/projects/learn.iris/src/learn.iris/main.go:10 +0x3b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/lib/go/src/runtime/time.go:59 +0xf9
github.com/valyala/fasthttp.init.1.func1()
        /home/pavel/projects/learn.iris/src/github.com/valyala/fasthttp/header.go:1372 +0x20
created by github.com/valyala/fasthttp.init.1
        /home/pavel/projects/learn.iris/src/github.com/valyala/fasthttp/header.go:1375 +0x30

goroutine 19 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [select]:
github.com/kataras/iris.(*websocketServer).serve(0xc820215ad0)
        /home/pavel/projects/learn.iris/src/github.com/kataras/iris/websocket.go:190 +0xe27
created by github.com/kataras/iris.newWebsocketServer
        /home/pavel/projects/learn.iris/src/github.com/kataras/iris/websocket.go:138 +0x3e8

```

**Comment by kataras** [comment]
If you upgrade to 1.7 this will be fixed but I will fix it also, right now.

Dublicated with: https://github.com/kataras/iris/issues/374

Thanks!

**Comment by pavelz** [comment]
Yes just got that.
THANKS!
