### ISSUE TITLE
a simple sample throws the "concurrent map writes" panic

### ISSUE THREAD

**Issue by smallnest** [kataras/iris#44]
I wrote a simple sample to test iris:

```
package main

import "github.com/kataras/iris"

func main() {
	api := iris.New()
	api.Get("/rest/hello", func(c *iris.Context) {
		c.Text("Hello world")
	})
	api.Listen(":8080")
}

```

but  when i run "wrk -t16 -c100 -d30s http://127.0.0.1:8080/rest/hello", it threw the below panic:

```
fatal error: concurrent map writes
goroutine 14 [running]:
runtime.throw(0x91ab70, 0x15)
        C:/Go/src/runtime/panic.go:530 +0x90 fp=0xc8201dd7f8 sp=0xc8201dd7e0
runtime.mapassign1(0x870e80, 0xc8201a8240, 0xc8201dd8c0, 0xc8201dd8d0)
        C:/Go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8201dd8a0 sp=0xc8201dd7f8
net/textproto.MIMEHeader.Set(0xc8201a8240, 0x8d15a0, 0xc, 0xc82017e120, 0x19)
        C:/Go/src/net/textproto/header.go:22 +0xc2 fp=0xc8201dd8f0 sp=0xc8201dd8a0
net/http.Header.Set(0xc8201a8240, 0x8d15a0, 0xc, 0xc82017e120, 0x19)
        C:/Go/src/net/http/header.go:31 +0x49 fp=0xc8201dd920 sp=0xc8201dd8f0
github.com/kataras/iris.(*Context).WriteText(0xc820172100, 0xc8, 0x8d2360, 0xb)
```

Am I wrong about using iris?

**Comment by xpbliss** [comment]
but when you visit ```http://127.0.0.1:8080/rest/hello``` . it's ok!

**Comment by smallnest** [comment]
Yes, If I use a client (a browser) visit this url, it is OK. But if use 100 clients to visit this url, simultaneously, this panic ocurred.

I believe it is concurrency issue.

**Comment by xpbliss** [comment]
when stress test for it .   sometime it raise up.

**Comment by kataras** [comment]
@smallnest Can you tell me what is your number of cores are you using? the Iris is checking that in order to use thread-safe router , if it's 1 core it is not using it, if it's more it uses locks and unlocks to the map, but this is not working for you, I 'll check it just tell me if you are manually set the maxcores and test it with maxcores(1) tell me if that fixed

**Comment by kataras** [comment]
@smallnest  can you update the iris (go get -u github.com/kataras/iris) and run your tests again?  Write if this is fixed here, also give me your code snippet you make the tests if you can, thanks

**Comment by smallnest** [comment]
I use aws.c2xlarge as the test server and it has  8 cores.
If I set "GOMAXPROCS=1".  iris works well.

I have updated iris but this issue still exists.

**Comment by kataras** [comment]
No it shouldn't have these kind of errors I tested it many times, hmm are you updated it from the development branch? ( download it by github and unzip it to the $GOPATH/src/github.com/kataras/iris) and try again please, it should work with any number of cores now ( I commented the checks for concurrency, is using the sync cache by default now)

**Comment by xpbliss** [comment]
another, when you stress test for iris many time (less than 20), it will crash .
ab -c 1000 -n 5000 http://localhost:8080/rest/hello

**Comment by kataras** [comment]
these are serious problems , take a look at the net/http issue I post before, tell me if that is the problem also check for -race conditions

**Comment by xpbliss** [comment]
a simple like the following:
```
package main
import "github.com/kataras/iris"
func main() {
    api := iris.New()
    api.Get("/rest/hello", func(c *iris.Context) {
        c.Text("Hello world")
    })
    api.Listen(":8080")
}
```

**Comment by smallnest** [comment]
Still crash in low press.
I have printed the context addess:
```
package main

import "github.com/kataras/iris"

func main() {
	api := iris.New()
	api.Get("/rest/hello", func(c *iris.Context) {
		println(c)
		c.Text("Hello world")
	})
	api.Listen(":8080")
}
```

It shows  many handlers use the same context. Is it the reason of crash because they write the same header simultaneously?
```
0xc82014c480
0xc82018a080
0xc82014c500
0xc82018a100
0xc82014c500
0xc82018a100
0xc82018a100
0xc82018a100
0xc82018a100
0xc82018a100
0xc82018a100
0xc82018a100
0xc82018a100
0xc82018a100
fatal error: concurrent map writes
0xc82018a100

goroutine 20 [running]:
runtime.throw(0x91ab70, 0x15)
        C:/Go/src/runtime/panic.go:530 +0x90 fp=0xc8201417f8 sp=0xc8201417e0
runtime.mapassign1(0x870e80, 0xc8201f4030, 0xc8201418c0, 0xc8201418d0)
        C:/Go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8201418a0 sp=0xc8201417f8
net/textproto.MIMEHeader.Set(0xc8201f4030, 0x8d15a0, 0xc, 0xc820170140, 0x19)
        C:/Go/src/net/textproto/header.go:22 +0xc2 fp=0xc8201418f0 sp=0xc8201418a0
net/http.Header.Set(0xc8201f4030, 0x8d15a0, 0xc, 0xc820170140, 0x19)
        C:/Go/src/net/http/header.go:31 +0x49 fp=0xc820141920 sp=0xc8201418f0
github.com/kataras/iris.(*Context).WriteText(0xc82018a100, 0xc8, 0x8d2360, 0xb)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/context.go:438 +0xc1 fp=0xc820141978 sp=0xc820141920
github.com/kataras/iris.(*Context).Text(0xc82018a100, 0x8d2360, 0xb)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/context.go:445 +0x3e fp=0xc8201419a0 sp=0xc820141978
main.main.func1(0xc82018a100)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/main.go:9 +0x53 fp=0xc8201419c0 sp=0xc8201419a0
github.com/kataras/iris.HandlerFunc.Serve(0x997ba0, 0xc82018a100)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/handler.go:47 +0x26 fp=0xc8201419d0 sp=0xc8201419c0
github.com/kataras/iris.(*Context).Do(0xc82018a100)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/context.go:348 +0x5d fp=0xc820141a10 sp=0xc8201419d0
```

**Comment by kataras** [comment]
```go

	iris.Get("/hello/:name", func(c *iris.Context) {
		// Retrieve the parameter name
		name := c.Param("name")
		c.Write("Hello %s", name)
	})

```

```
ab -c 10000 -n 50000 http://localhost:8080/hello/name 
```

@xpbliss This is working on me without errors

**Comment by kataras** [comment]
@smallnest  yes it seems that is a issue thread at the net/http golang's package also, try this:

```go
package main

import "github.com/kataras/iris"

func main() {
    api := iris.New()
    api.Get("/rest/hello", func(c *iris.Context) {
        ctx:= c.Clone()
        println(ctx)
        ctx.Write("Hello world")
    })
    api.Listen(":8080")
}

````

**Comment by xpbliss** [comment]
```package main
import "github.com/kataras/iris"
func main() {
    api := iris.New()
    api.Get("/hello", func(c *iris.Context) {
        c.Text("Hello world")
    })
    api.Listen(":8080")
}
```
when you execute ```ab -c 10000 -n 50000 http://localhost:8080/hello```  repeat, more  than 20 ,it will crash?

**Comment by smallnest** [comment]
@kataras  I have test your codes:
 
package main
```

import "github.com/kataras/iris"

func main() {
    api := iris.New()
    api.Get("/rest/hello", func(c *iris.Context) {
        ctx:= c.Clone()
        println(ctx)
        ctx.Write("Hello world")
    })
    api.Listen(":8080")
}
```

It crashed becuase of invalid memory address

```
0xc820e60400
2016/03/28 03:54:00 http: panic serving 127.0.0.1:51865: runtime error: invalid memory address or nil pointer dereference
goroutine 49 [running]:
net/http.(*conn).serve.func1(0xc820180000)
        C:/Go/src/net/http/server.go:1389 +0xc1
panic(0x83c640, 0xc82000a0f0)
        C:/Go/src/runtime/panic.go:426 +0x4e9
io.WriteString(0x0, 0x0, 0xc82025b160, 0xb, 0x0, 0x0, 0x0)
        C:/Go/src/io/io.go:281 +0x12b
github.com/kataras/iris.(*MemoryWriter).WriteString(0xc820e60400, 0xc82025b160, 0xb, 0xc8202c56b0, 0x0, 0x0)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/memory_writer.go:100 +0x93
io.WriteString(0x7fc9e49d2f48, 0xc820e60400, 0xc82025b160, 0xb, 0xc820e60400, 0x0, 0x0)
        C:/Go/src/io/io.go:279 +0xaa
github.com/kataras/iris.(*Context).Write(0xc820e60400, 0x8d2360, 0xb, 0x0, 0x0, 0x0)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/context.go:190 +0xc1
main.main.func1(0xc820e60380)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/main.go:10 +0x2d8
github.com/kataras/iris.HandlerFunc.Serve(0x997bc0, 0xc820e60380)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/handler.go:47 +0x26
github.com/kataras/iris.(*Context).Do(0xc820e60380)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/context.go:348 +0x5d
github.com/kataras/iris.(*Router).find(0xc82013e100, 0x8c6578, 0x3, 0xc82014a070, 0x0, 0x0, 0x7fc9e4ac3300, 0xc8209eb044, 0xb, 0xc820e60380, ...)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/router.go:141 +0x129
github.com/kataras/iris.(*Router).processRequest(0xc82013e100, 0xc820e60380, 0xb37ee8)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/router.go:185 +0x1aa
github.com/kataras/iris.(*MemoryRouter).ServeHTTP(0xc8201420c0, 0x7fc9e49d2e98, 0xc8201760d0, 0xc8201d00e0)
        C:/eclipse_workspace/Jax-RS-Performance-Comparison/go-restful/src/github.com/kataras/iris/router_memory.go:87 +0x24d
net/http.serverHandler.ServeHTTP(0xc82016e000, 0x7fc9e49d2e98, 0xc8201760d0, 0xc8201d00e0)
        C:/Go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820180000)
        C:/Go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2137 +0x44e
0xc820f24100
0xc820d8f380
0xc820f00200
0xc820e7ab80
0xc820e12d00
0xc820f56100
0xc820e20a80
2016/03/28 03:54:00 http: panic serving 127.0.0.1:51878: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:

```

**Comment by kataras** [comment]
@smallnest  , @xpbliss  sorry for late, I  found what's the wrong, the problem is only this ctx.ResponseWriter.Header().Set(ContentType, ContentTEXT+" ;charset="+Charset)

 I am trying to fix it I am near to this, please wait here for a fix

**Comment by kataras** [comment]
@xpbliss @smallnest  can you test it now? ( you may get some logs but it's ok )

**Comment by smallnest** [comment]
@kataras Now  it work well except some logs "http: multiple response.WriteHeader calls"

**Comment by kataras** [comment]
@smallnest  Just fix it :) I forgot to do it to the other router, now no logs all works fine test it

**Comment by xpbliss** [comment]
occasionally，it occur ``` http: multiple response.WriteHeader calls```

**Comment by kataras** [comment]
@xpbliss  I know i told you u may get some logs, I just fix it also test again :)

**Comment by xpbliss** [comment]
About httpserver,
 you may learn from ```github.com/facebookgo/grace/gracehttp```

**Comment by kataras** [comment]
@xpbliss  what do you mean laern about httpserver? ( your link is 404)

**Comment by xpbliss** [comment]
https://github.com/facebookgo/grace
it is a good httpserver.

**Comment by kataras** [comment]
it;s just a graceful restart for Go servers. Maybe you should look inside the [https://github.com/kataras/iris/tree/examples/thirdparty_graceful](https://github.com/kataras/iris/tree/examples/thirdparty_graceful)

**Comment by kataras** [comment]
Thanks for your issues I appriciate it! You help a lot today

**Comment by smallnest** [comment]
Thanks. And there are still those logs : " http: multiple response.WriteHeader calls"

**Comment by kataras** [comment]
Let me look that again, on me it has go 2 lines of logs, I though I fix it I ran it 10 times and no logs after a change, wait

**Comment by kataras** [comment]
You have right it's not fixed

**Comment by kataras** [comment]
@smallnest  can you test again? I  think totally fix

**Comment by smallnest** [comment]
This issue is fixed. Now there are no logs.

BTW， maybe you can run benchmark test. I'm a little worried about its performance because you has added the lock in SetHeader and SetContentType

**Comment by kataras** [comment]
The benchmarks are from julien's repository http-routing-benchmark they have not relationship with the locks I added, I am careful on that. you can re-run the benchmarks ( I did before commit) no performance issue but thanks you !!

**Comment by smallnest** [comment]
I test its benchmark on my laptop and Iris's performance is still good.

```
PASS
BenchmarkGin_Param           	20000000	       114 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_Param          	30000000	        70.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_Param       	  200000	      8865 ns/op	    1104 B/op	      11 allocs/op

BenchmarkGin_Param5          	10000000	       196 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_Param5         	20000000	        68.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_Param5      	  200000	     10335 ns/op	    1232 B/op	      11 allocs/op

BenchmarkGin_Param20         	 2000000	       627 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_Param20     	   50000	     28972 ns/op	    3597 B/op	      13 allocs/op

BenchmarkGin_ParamWrite      	 5000000	       281 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_ParamWrite     	10000000	       217 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_ParamWrite  	  200000	     12281 ns/op	    1208 B/op	      15 allocs/op

BenchmarkGin_GithubStatic    	10000000	       160 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GithubStatic   	30000000	        60.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_GithubStatic	  100000	     21221 ns/op	     784 B/op	      10 allocs/op

BenchmarkGin_GithubParam     	10000000	       258 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GithubParam    	30000000	        58.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_GithubParam 	  100000	     16994 ns/op	    1136 B/op	      11 allocs/op

BenchmarkGin_GithubAll       	   30000	     48223 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GithubAll      	   50000	     24977 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_GithubAll   	     200	   6803166 ns/op	  228218 B/op	    2483 allocs/op

BenchmarkGin_GPlusStatic     	20000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GPlusStatic    	30000000	        59.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_GPlusStatic 	  300000	      5640 ns/op	     784 B/op	      10 allocs/op

BenchmarkGin_GPlusParam      	10000000	       152 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GPlusParam     	20000000	        68.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_GPlusParam  	  200000	      7204 ns/op	    1104 B/op	      11 allocs/op

BenchmarkGin_GPlus2Params    	10000000	       194 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GPlus2Params   	20000000	        61.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_GPlus2Params	  100000	     16790 ns/op	    1232 B/op	      15 allocs/op

BenchmarkGin_GPlusAll        	 1000000	      2508 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_GPlusAll       	 1000000	      1426 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_GPlusAll    	   10000	    125826 ns/op	   14448 B/op	     165 allocs/op

BenchmarkGin_ParseStatic     	20000000	       120 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_ParseStatic    	20000000	        60.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_ParseStatic 	  200000	      6732 ns/op	     784 B/op	      10 allocs/op

BenchmarkGin_ParseParam      	10000000	       169 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_ParseParam     	20000000	        74.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_ParseParam  	  200000	      7545 ns/op	    1104 B/op	      11 allocs/op

BenchmarkGin_Parse2Params    	10000000	       149 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_Parse2Params   	20000000	        65.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_Parse2Params	  200000	      7001 ns/op	    1136 B/op	      11 allocs/op

BenchmarkGin_ParseAll        	  300000	      5178 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_ParseAll       	  500000	      3201 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_ParseAll    	   10000	    206694 ns/op	   25600 B/op	     276 allocs/op

BenchmarkGin_StaticAll       	   50000	     36190 ns/op	       0 B/op	       0 allocs/op
BenchmarkIris_StaticAll      	  100000	     19641 ns/op	       0 B/op	       0 allocs/op
BenchmarkMartini_StaticAll   	     500	   3353277 ns/op	  132819 B/op	    2178 allocs/op
ok  	github.com/iris-contrib/go-http-routing-benchmark	91.902s

```

**Comment by kataras** [comment]
Yeah Iris is far the fastest, thanks you for your help!
