### ISSUE TITLE
fatal error: concurrent map writes with few thousands requests

### ISSUE THREAD

**Issue by tuxlinuxien** [kataras/iris#48]
```
2016/03/30 14:37:29 http: multiple response.WriteHeader calls
...
fatal error: concurrent map writes

goroutine 42 [running]:
runtime.throw(0x951040, 0x15)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc82017c810 sp=0xc82017c7f8
runtime.mapassign1(0x8a1ea0, 0xc820192540, 0xc82017c8d8, 0xc82017c8e8)
	/usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc82017c8b8 sp=0xc82017c810
net/textproto.MIMEHeader.Set(0xc820192540, 0x9050f0, 0xc, 0xc82013e900, 0x19)
	/usr/local/go/src/net/textproto/header.go:22 +0xc2 fp=0xc82017c908 sp=0xc82017c8b8
net/http.Header.Set(0xc820192540, 0x9050f0, 0xc, 0xc82013e900, 0x19)
	/usr/local/go/src/net/http/header.go:31 +0x49 fp=0xc82017c938 sp=0xc82017c908
github.com/kataras/iris.(*Context).WriteText(0xc820152300, 0xc8, 0x8fa878, 0x2)
	/go/src/github.com/kataras/iris/context.go:435 +0xc1 fp=0xc82017c990 sp=0xc82017c938
datapro/storage/interfaces/http.setArrRawHandler(0xc820152300)
	/go/src/datapro/storage/interfaces/http/server.go:98 +0x89 fp=0xc82017c9d0 sp=0xc82017c990
github.com/kataras/iris.HandlerFunc.Serve(0x9d2ba0, 0xc820152300)
	/go/src/github.com/kataras/iris/handler.go:47 +0x26 fp=0xc82017c9e0 sp=0xc82017c9d0
github.com/kataras/iris.(*Context).Do(0xc820152300)
	/go/src/github.com/kataras/iris/context.go:345 +0x5d fp=0xc82017ca20 sp=0xc82017c9e0
github.com/kataras/iris.(*Context).Redo(0xc820152300, 0x7f30bc46e130, 0xc8201449c0, 0xc820187180)
	/go/src/github.com/kataras/iris/context.go:161 +0x87 fp=0xc82017ca50 sp=0xc82017ca20
github.com/kataras/iris.(*MemoryRouter).ServeHTTP(0xc8201380f0, 0x7f30bc46e130, 0xc8201449c0, 0xc820187180)
	/go/src/github.com/kataras/iris/router_memory.go:80 +0xd3 fp=0xc82017cb80 sp=0xc82017ca50
net/http.serverHandler.ServeHTTP(0xc820152100, 0x7f30bc46e130, 0xc8201449c0, 0xc820187180)
	/usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc82017cbe0 sp=0xc82017cb80
net/http.(*conn).serve(0xc820168b00)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc82017cfa8 sp=0xc82017cbe0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82017cfb0 sp=0xc82017cfa8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

code:

```
func setArrRawHandler(c *iris.Context) {
    c.Write("OK")
}

func start() {
   dbH := iris.Party("/db")
    {
        dbH.Post("/setarrraw/:sid/:rid/:rv/:klens", setArrRawHandler)
    }
    iris.Listen(":8080")
}
```

**Comment by kataras** [comment]
Dublicate with https://github.com/kataras/iris/issues/44 . I had fixed it , it occurs errors again ??

**Comment by kataras** [comment]
@tuxlinuxien Man this is working I tested again and again with c.Write and c.Text, maybe you do something whrong ( again) ? ...
