### ISSUE TITLE
How to bind multi domain?

### ISSUE THREAD

**Issue by xingdonghai** [kataras/iris#482]
How to bind multi domain? like this: abc.com:80, def.com:80？And disable access to other domain names

**Comment by kataras** [comment]
Define a subdomain : 
```go
defSubdomain:= iris.Party("def.")
{
   defSubdomain.Get("/", abcIndexHandler)
   defSubdomain.Get("/home", abcHomeHandler)
}

iris.Listen("abc.com:80")
```

for the second question, about disable other domain names,  (subdomaindef.  is already 'binded' on def.abc.com) so to 'disallow' other domains make use of a global middleware

```go
iris.Use(func(ctx *iris.Context){
   h := ctx.HostString()
    // if host is not abc.com then send a server internal error
   if h !="abc.com" {
     ctx.EmitError(500)
     return
  }
  // if is abc.com then continue to th ehandler
   ctx.Next()
})

```

You didn't read the book or the examples...

**Comment by xingdonghai** [comment]
No, i has read all examples, but not found about this informations. I want to bind multiple primary domains at the same time, like nginx config: 

`server_name www.abc.com www.def.com;`

And them primary domains has some subdomains....

**Comment by kataras** [comment]
So you need multiple `domains` to point on the same `route handlers` ? **There is an example of this** [here](https://github.com/iris-contrib/examples/tree/master/custom_fasthttp_server), but you have two solution:


###1 

```go
import (
   "github.com/kataras/iris"
   "github.com/valyala/fasthttp"
)

abc_com:= iris.New()

abc_com.Get("/", myIndex)
abc_com.Party("www.").Get("/", myIndex)


// Build is needed to execute manually if you want to bind it's Router to another web server, as we do here
abc_com.Build()

// start the first server with iris.Listen
go abc_com.Listen("abc.com")

// create our custom fasthttp server and assign the Handler/Router
fsrv := &fasthttp.Server{Handler: abc_com.Router}
fsrv.ListenAndServe("def.com")
```


###2 

```go
abc_com:= iris.New()

abc_com.Get("/", myIndex)
abc_com.Party("www.").Get("/", myIndex)

// Build the router( you can do with .Listen and wait 1 second but it's better to Build first if you need to use the Router later.
abc_com.Build()

// define a new iris and point to that router
def_com := iris.New()
def_com.Router = server_name.Router

//start the servers with their domains
go server_name.Listen("abc.com")
def_com.Listen("def.com")


```

Now, primary domains have their own subdomains (www. here but you can define unlimited number of those), please read carefully the next time, thank you!

**Comment by xingdonghai** [comment]
Hello, examples does not run.

**1**

```
package main

import (
	"github.com/kataras/iris"
	"github.com/valyala/fasthttp"
)

func main() {
	abc_com := iris.New()

	abc_com.Get("/", myIndex)
	abc_com.Party("www.").Get("/", myIndex)

	// Build the router( you can do with .Listen and wait 1 second but it's better to Build first if you need to use the Router later.
	abc_com.Build()

	go abc_com.Listen("abc.com:8088")

	fsrv := &fasthttp.Server{Handler: abc_com.Router}
	fsrv.ListenAndServe("def.com:8088")
}

func myIndex(ctx *iris.Context) {
	ctx.WriteString("aaaa")
}
```
Output:

```
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 4.6.0 

Mon, 17 Oct 2016 21:00:08 GMT: Running at 0.0.0.0:8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbbfea]

goroutine 5 [running]:
panic(0x6157e0, 0xc42000c0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/valyala/fasthttp.(*Server).Serve(0x0, 0x9b2fe0, 0xc42002c038, 0x0, 0x59b61)
	/Users/donghai/vagrant/go/src/github.com/valyala/fasthttp/server.go:1242 +0x5a
github.com/kataras/iris.(*Framework).Serve.func2(0xc42019b290, 0x9b2fe0, 0xc42002c038)
	/Users/donghai/vagrant/go/src/github.com/kataras/iris/iris.go:449 +0x43
created by github.com/kataras/iris.(*Framework).Serve
	/Users/donghai/vagrant/go/src/github.com/kataras/iris/iris.go:449 +0x155
```


**2**
```
package main

import (
	"github.com/kataras/iris"
)

func main() {
	abc_com:= iris.New()

	abc_com.Get("/", myIndex)
	abc_com.Party("www.").Get("/", myIndex)

	// Build the router( you can do with .Listen and wait 1 second but it's better to Build first if you need to use the Router later.
	abc_com.Build()

	// define a new iris and point to that router
	def_com := iris.New()
	def_com.Router = abc_com.Router

	//start the servers with their domains
	go abc_com.Listen("abc.com:8088")
	def_com.Listen("def.com:8088")
}

func myIndex(ctx *iris.Context) {
	ctx.WriteString("aaaa")
}
```

Output:
```
         _____      _
        |_   _|    (_)
          | |  ____ _  ___
          | | | __|| |/ __|
         _| |_| |  | |\__ \
        |_____|_|  |_||___/ 4.6.0 

Mon, 17 Oct 2016 21:02:57 GMT: Running at 0.0.0.0:8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf1b6a]

goroutine 35 [running]:
panic(0x6157e0, 0xc42000c0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/valyala/fasthttp.(*Server).Serve(0x0, 0x9b2fe0, 0xc420248030, 0x0, 0x59b51)
	/Users/donghai/vagrant/go/src/github.com/valyala/fasthttp/server.go:1242 +0x5a
github.com/kataras/iris.(*Framework).Serve.func2(0xc420250000, 0x9b2fe0, 0xc420248030)
	/Users/donghai/vagrant/go/src/github.com/kataras/iris/iris.go:449 +0x43
created by github.com/kataras/iris.(*Framework).Serve
	/Users/donghai/vagrant/go/src/github.com/kataras/iris/iris.go:449 +0x155
```

And, I want to listen only one port for multi domains

**Comment by kataras** [comment]
For the first example, I'm sorry you have to put `abc.com.Listen` to the last:

```go
    fsrv := &fasthttp.Server{Handler: abc_com.Router}
    fsrv.ListenAndServe("def.com:8088")

    go abc_com.Listen("abc.com:8088")
```

For your second example, it runs on me, but again just discard the second, it's the same with the first.


If you want one port then you have use nginx or caddy , iris is not a proxy, it's a web framework, build your app with iris and make use the nginx

**Comment by kataras** [comment]
For the first example, I'm sorry you have to put `abc.com.Listen` to the last:

```go
    fsrv := &fasthttp.Server{Handler: abc_com.Router}
    go fsrv.ListenAndServe("def.com:8088")

    abc_com.Listen("abc.com:8088")
```

For your second example, it runs on me, but again just discard the second, it's the same with the first.


If you want one port then you have use nginx or caddy , iris is not a proxy, it's a web framework, build your app with iris and make use the nginx
