### ISSUE TITLE
runtime error using HTML Template Engine 

### ISSUE THREAD

**Issue by yaa110** [kataras/iris#484]
- Version : **4.6.0**
- Latest Commit: **9a0ef48**

- Operating System: **Ubuntu 16.04.1 64 bit**
- Go Version: **1.7.1**

- [x] I have read the [book (template-engines)](https://docs.iris-go.com/template-engines.html), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------

Hi, using the following example:
```go
func main() {
	iris.Config.DisableBanner = true
	iris.Config.DisableTemplateEngines = true
	iris.Config.LoggerPreffix = "[CustomPrefix]"
	iris.Config.IsDevelopment = true

	iris.Post("/login", Login)
}

func Login(c *iris.Context) {
	c.MustRender("login.html", struct{ Name string }{Name: "test"})
}
```
```html
<!-- ./templates/login.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <p>{{.Name}}</p>
</body>
</html>
```

I got the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x671566]

goroutine 67 [running]:
panic(0xc35f60, 0xc42000c100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/kataras/go-template.(*Mux).ExecuteWriter(0xc4202241b0, 0x1117d60, 0xc4202170d8, 0xd24a99, 0xa, 0xc45560, 0xc4202365d0, 0x0, 0x0, 0x0, ...)
	/home/yaa110/Projects/Go/src/github.com/kataras/go-template/mux.go:143 +0x96
github.com/kataras/iris.(*templateEngines).render(0xc42021cb80, 0xffffffffffffff01, 0xc42065c240, 0xd24a99, 0xa, 0xc45560, 0xc4202365d0, 0x0, 0x0, 0x0, ...)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/template.go:118 +0x2f0
github.com/kataras/iris.(*templateEngines).renderFile(0xc42021cb80, 0xc42065c240, 0xd24a99, 0xa, 0xc45560, 0xc4202365d0, 0x0, 0x0, 0x0, 0xc420236520, ...)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/template.go:125 +0x99
github.com/kataras/iris.(*Context).RenderWithStatus(0xc42065c240, 0xc8, 0xd24a99, 0xa, 0xc45560, 0xc4202365d0, 0x0, 0x0, 0x0, 0xc45560, ...)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/context.go:639 +0xc3
github.com/kataras/iris.(*Context).Render(0xc42065c240, 0xd24a99, 0xa, 0xc45560, 0xc4202365d0, 0x0, 0x0, 0x0, 0x443655, 0x10)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/context.go:659 +0xbf
github.com/kataras/iris.(*Context).MustRender(0xc42065c240, 0xd24a99, 0xa, 0xc45560, 0xc4202365d0, 0x0, 0x0, 0x0)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/context.go:666 +0x9b
github.com/yaa110/bufe-ketab-api/app/controller.AdminLoginPage(0xc42065c240)
	/home/yaa110/Projects/Go/src/github.com/yaa110/bufe-ketab-api/app/controller/admin.go:36 +0xbd
github.com/kataras/iris.HandlerFunc.Serve(0xd96a98, 0xc42065c240)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/http.go:253 +0x30
github.com/kataras/iris.(*Context).Do(0xc42065c240)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/context.go:114 +0x49
github.com/kataras/iris.(*serveMux).BuildHandler.func1(0xc42065c240)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/http.go:1178 +0x932
github.com/kataras/iris.(*Framework).Build.func1.1(0xc420216d80)
	/home/yaa110/Projects/Go/src/github.com/kataras/iris/iris.go:368 +0x5a
github.com/valyala/fasthttp.(*Server).serveConn(0xc4200a4000, 0x1124d60, 0xc420128060, 0xc420663701, 0x101)
	/home/yaa110/Projects/Go/src/github.com/valyala/fasthttp/server.go:1528 +0x573
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x1124d60, 0xc420128060, 0xc420663758, 0x1)
	/home/yaa110/Projects/Go/src/github.com/valyala/fasthttp/server.go:1245 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc420222000, 0xc420113fc0)
	/home/yaa110/Projects/Go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xde
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc420222000, 0xc420113fc0, 0xbcd020, 0xc420113fc0)
	/home/yaa110/Projects/Go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/yaa110/Projects/Go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x111
exit status 2
```

**Comment by kataras** [comment]
Yes, you had ` iris.Config.DisableTemplateEngines = true` and used `Render/MustRender` which causes a panic, this is OK but I will make it to show a message that templates are disabled :)
