### ISSUE TITLE
Django template inheritance doesn't work with bindata

### ISSUE THREAD

**Issue by hrwebasst** [kataras/iris#535]
- Version : **5.0.1**

- Operating System:

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

Using this works great for templates to be embedded.
`iris.UseTemplate(django.New()).Directory("./assets/templates", ".html").Binary(Asset, AssetNames)`

However when doing `{% extends "base.html" %}` It will error out looking for the physical file.

```
[IRIS] 2016/11/15 19:24:57 [Error (where: fromfile) in assets/templates/base.html] open /assets/templates/base.html: no such file or directory
panic: [Error (where: fromfile) in assets/templates/base.html] open /assets/templates/base.html: no such file or directory

goroutine 1 [running]:
panic(0xa2d240, 0xc4202ac3f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
log.(*Logger).Panic(0xc420067900, 0xc4201dfc30, 0x1, 0x1)
	/usr/local/go/src/log/log.go:206 +0xc7
github.com/kataras/iris.(*Framework).Build.func1()
	/go/src/github.com/kataras/iris/iris.go:342 +0x7af
sync.(*Once).Do(0xc42019fe88, 0xc4201dfc98)
	/usr/local/go/src/sync/once.go:44 +0xdb
github.com/kataras/iris.(*Framework).Build(0xc42019fe40)
	/go/src/github.com/kataras/iris/iris.go:413 +0x4c
github.com/kataras/iris.(*Framework).Serve(0xc42019fe40, 0xe2e780, 0xc420038298, 0x0, 0x0)
	/go/src/github.com/kataras/iris/iris.go:437 +0xc4
github.com/kataras/iris.(*Framework).Listen(0xc42019fe40, 0xc420222d00, 0xc)
	/go/src/github.com/kataras/iris/iris.go:504 +0xc6
github.com/kataras/iris.Listen(0xb18d1f, 0x5)
	/go/src/github.com/kataras/iris/iris.go:484 +0x41
main.main()
	cmd.go:70 +0x5ee
```

Relevant: 

https://github.com/flosch/pongo2/issues/68
https://gist.github.com/diyan/63f2169e6ccc85c869d7c5f19d7b211e

**Comment by hrwebasst** [comment]
I realize now I should post this in the templates portion of the project. My apologies
