### ISSUE TITLE
Conflicts with wildcard in routes

### ISSUE THREAD

**Issue by dlion** [kataras/iris#547]
- Version : **5.0.1**

- Operating System: Arch Linux

- [x] I have read the [book](https://docs.iris-go.com), [examples](https://github.com/iris-contrib/examples), [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and **I'm sure that this issue is not posted** & answered before.

--------------

I have this code:
```go
 //Conf
        iris.UseTemplate(django.New()).Directory("./templates", ".html")
        iris.Config.Gzip = true

        //Middleware to init the db
        iris.UseFunc(initDB)

        /**
         * Routes
         */

        //Home
        iris.Get("/", home)

        //getURL
        iris.Get("/:url", getUrl)
        iris.Post("/:url", postUrl)

        //Show result
        iris.Get("/result/:bam", func(ctx *iris.Context) {
                ctx.Render("result.html", map[string]interface{}{"bam": ctx.Param("bam")})
        })

        //Listen
        iris.Listen(":8080")
```
but when I run iris I receive this error:

```
[IRIS] 2016/11/28 14:10:32 Error: Router: Path's part: 'result/:bam' conflicts with wildcard ':url' in the route path: '/result/:bam' !
panic: Error: Router: Path's part: 'result/:bam' conflicts with wildcard ':url' in the route path: '/result/:bam' !


goroutine 1 [running]:
panic(0xa96ee0, 0xc420242b50)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
log.(*Logger).Panic(0xc4200734f0, 0xc4201f5b68, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:206 +0xc7
github.com/kataras/iris.(*serveMux).build(0xc4200b3b80, 0x51c94d, 0xc4201eafc0)
        /home/dlion/go/src/github.com/kataras/iris/http.go:1010 +0x2de
github.com/kataras/iris.(*serveMux).BuildHandler(0xc4200b3b80, 0xc420246e60)
        /home/dlion/go/src/github.com/kataras/iris/http.go:1076 +0x2f
github.com/kataras/iris.(*Framework).Build.func1()
        /home/dlion/go/src/github.com/kataras/iris/iris.go:362 +0x49c
sync.(*Once).Do(0xc4201d5ee8, 0xc4201f5cf8)
        /usr/lib/go/src/sync/once.go:44 +0xdb
github.com/kataras/iris.(*Framework).Build(0xc4201d5ea0)
        /home/dlion/go/src/github.com/kataras/iris/iris.go:402 +0x4c
github.com/kataras/iris.(*Framework).Serve(0xc4201d5ea0, 0x10ae420, 0xc420084288, 0x0, 0x0)
        /home/dlion/go/src/github.com/kataras/iris/iris.go:426 +0xc4
github.com/kataras/iris.(*Framework).Listen(0xc4201d5ea0, 0xc4202426f0, 0xc)
        /home/dlion/go/src/github.com/kataras/iris/iris.go:493 +0xc6
github.com/kataras/iris.Listen(0xb7b061, 0x5)
        /home/dlion/go/src/github.com/kataras/iris/iris.go:473 +0x41
main.main()
        /home/dlion/sources/Glip/main.go:39 +0x297
exit status 2
```
Why ?
The routes should be different

**Comment by dlion** [comment]
Ok I figure out by myself why this happen, because the route /:url match the route /result/:url too.
I solved using routes like: `/url/:url` and `/result/url`
