### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by mirchencom** [kataras/iris#662]
```
2017/06/30 17:11:18 http: panic serving 127.0.0.1:50644: runtime error: index out of range
goroutine 1240 [running]:
net/http.(*conn).serve.func1(0xc043ecd0e0)
        C:/Go1.9/src/net/http/server.go:1693 +0x180
panic(0xc317a0, 0x10c1d70)
        C:/Go1.9/src/runtime/panic.go:491 +0x2b0
math/rand.(*rngSource).Uint64(...)
        C:/Go1.9/src/math/rand/rng.go:246
math/rand.(*rngSource).Int63(0xc042188000, 0x40)
        C:/Go1.9/src/math/rand/rng.go:231 +0x2b0
gopkg.in/kataras/iris.v6/adaptors/websocket.random(0x40, 0x90, 0x0, 0xc044f469f0)
        E:/IM/src/gopkg.in/kataras/iris.v6/adaptors/websocket/message.go:170 +0x9e
gopkg.in/kataras/iris.v6/adaptors/websocket.randomString(0x40, 0xc045103cc0, 0xc045148600)
        E:/IM/src/gopkg.in/kataras/iris.v6/adaptors/websocket/message.go:187 +0x40
gopkg.in/kataras/iris.v6/adaptors/websocket.glob..func1(0xc0421c28c0, 0xe5, 0xc000000000)
        E:/IM/src/gopkg.in/kataras/iris.v6/adaptors/websocket/config.go:33 +0x3f
gopkg.in/kataras/iris.v6/adaptors/websocket.(*server).handleConnection(0xc042214680, 0xc0421c28c0, 0x1093420, 0xc045103cc0)
        E:/IM/src/gopkg.in/kataras/iris.v6/adaptors/websocket/server.go:210 +0x79
gopkg.in/kataras/iris.v6/adaptors/websocket.(*server).Handler.func1(0xc0421c28c0)
        E:/IM/src/gopkg.in/kataras/iris.v6/adaptors/websocket/server.go:203 +0x222
gopkg.in/kataras/iris%2ev6.HandlerFunc.Serve(0xc04224cf80, 0xc0421c28c0)
        E:/IM/src/gopkg.in/kataras/iris.v6/handler.go:36 +0x45
gopkg.in/kataras/iris%2ev6.(*Context).Do(0xc0421c28c0)
        E:/IM/src/gopkg.in/kataras/iris.v6/context.go:233 +0xa8
gopkg.in/kataras/iris.v6/adaptors/httprouter.(*serveMux).buildHandler.func1.1(0xc0421c28c0)
        E:/IM/src/gopkg.in/kataras/iris.v6/adaptors/httprouter/httprouter.go:729 +0xca5
gopkg.in/kataras/iris%2ev6.(*contextPool).Run(0xc04224c980, 0x108fa60, 0xc045298fc0, 0xc045068800, 0xc042316d40)
        E:/IM/src/gopkg.in/kataras/iris.v6/context.go:195 +0x7a
gopkg.in/kataras/iris.v6/adaptors/httprouter.(*serveMux).buildHandler.func1(0x108fa60, 0xc045298fc0, 0xc045068800)
        E:/IM/src/gopkg.in/kataras/iris.v6/adaptors/httprouter/httprouter.go:698 +0x149
net/http.HandlerFunc.ServeHTTP(0xc042249770, 0x108fa60, 0xc045298fc0, 0xc045068800)
        C:/Go1.9/src/net/http/server.go:1914 +0x59
gopkg.in/kataras/iris%2ev6.(*Router).ServeHTTP(0xc042128480, 0x108fa60, 0xc045298fc0, 0xc045068800)
        E:/IM/src/gopkg.in/kataras/iris.v6/router.go:138 +0x79
net/http.serverHandler.ServeHTTP(0xc042214820, 0x108fa60, 0xc045298fc0, 0xc045068800)
        C:/Go1.9/src/net/http/server.go:2610 +0xc4
net/http.(*conn).serve(0xc043ecd0e0, 0x10901a0, 0xc044c15480)
        C:/Go1.9/src/net/http/server.go:1797 +0x843
created by net/http.(*Server).Serve
        C:/Go1.9/src/net/http/server.go:2711 +0x384
```

**Comment by Hugo-Huang** [comment]
I also meet the problem, why this issue be closed without any reply? who can explain it?
