### ISSUE TITLE
Error in ReadJSON and ReadXML

### ISSUE THREAD

**Issue by shiena** [kataras/iris#70]
# Environment

* go version go1.6.2 windows/amd64
* commit 870eaa716d5000780b6f2cd3313c88f03a31c786

# Reproduce

## Test code

```jsonxml.go:go
package main

import (
	"fmt"
	"github.com/kataras/iris"
)

type Request struct {
	Message string
}

func main() {
	iris.Post("/json", func(c *iris.Context) {
		req := &Request{}
		err := c.ReadJSON(req)
		if err != nil {
			fmt.Errorf("%s", err)
		} else {
			fmt.Printf("%v", req)
		}

		c.Done()
	})
	iris.Post("/xml", func(c *iris.Context) {
		req := &Request{}
		err := c.ReadXML(req)
		if err != nil {
			fmt.Errorf("%s", err)
		} else {
			fmt.Printf("%v", req)
		}

		c.Done()
	})

	iris.Listen(":8080")
}
```

## Pattern XML

```
$ curl -H Content-Type:application/xml -d'<Message>test</Message>' http://localhost:8080/xml
```

```
2016/04/27 21:28:35 panic: runtime error: invalid memory address or nil pointer dereference
Stack trace:
goroutine 33 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	C:/go/src/runtime/debug/stack.go:24 +0x87
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).workerFunc.func1(0xc0820e0380, 0xc082199ed0)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:207 +0x5a
panic(0x8e6de0, 0xc082002090)
	C:/go/src/runtime/panic.go:443 +0x4f7
github.com/kataras/iris.(*Context).ReadXML(0xc08218a000, 0x7f1980, 0xc082174230, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/context.go:585 +0x38a
main.main.func2(0xc08218a000)
	C:/Users/shiena/go/src/jsonxml.go:26 +0x75
github.com/kataras/iris.HandlerFunc.Serve(0xa6c090, 0xc08218a000)
	C:/Users/shiena/go/src/github.com/kataras/iris/handler.go:77 +0x2d
github.com/kataras/iris.(*Context).Do(0xc08218a000)
	C:/Users/shiena/go/src/github.com/kataras/iris/context.go:337 +0x64
github.com/kataras/iris.(*tree).serve(0xc082012a80, 0xc08217e000)
	C:/Users/shiena/go/src/github.com/kataras/iris/tree.go:185 +0x1e0
github.com/kataras/iris.(*Router).ServeRequest(0xc082010a50, 0xc08217e000)
	C:/Users/shiena/go/src/github.com/kataras/iris/router.go:196 +0x194
github.com/kataras/iris.(IRouter).ServeRequest-fm(0xc08217e000)
	C:/Users/shiena/go/src/github.com/kataras/iris/station.go:231 +0x46
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*Server).serveConn(0xc082038a00, 0xed5b20, 0xc082120010, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/server.go:1438 +0x752
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*Server).(github.com/kataras/iris/vendor/github.com/valyala/fasthttp.serveConn)-fm(0xed5b20, 0xc082120010, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/server.go:1176 +0x49
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0820e0380, 0xc082107460)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:224 +0x123
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0820e0380, 0xc082107460, 0x7f0840, 0xc082107460)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:183 +0x32
created by github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).getCh
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:185 +0x1f0
```

## Pattern JSON

```
$ curl -H Content-Type:application/json -d'{"Message":"test"}' http://localhost:8080/json
```

```
2016/04/27 21:33:17 panic: runtime error: invalid memory address or nil pointer dereference
Stack trace:
goroutine 49 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	C:/go/src/runtime/debug/stack.go:24 +0x87
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).workerFunc.func1(0xc0820e0380, 0xc082195ed0)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:207 +0x5a
panic(0x8e6de0, 0xc082002090)
	C:/go/src/runtime/panic.go:443 +0x4f7
github.com/kataras/iris.(*Context).ReadJSON(0xc0821c0000, 0x7f1980, 0xc0821a8c20, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/context.go:553 +0x250
main.main.func1(0xc0821c0000)
	C:/Users/shiena/go/src/jsonxml.go:15 +0x75
github.com/kataras/iris.HandlerFunc.Serve(0xa6c088, 0xc0821c0000)
	C:/Users/shiena/go/src/github.com/kataras/iris/handler.go:77 +0x2d
github.com/kataras/iris.(*Context).Do(0xc0821c0000)
	C:/Users/shiena/go/src/github.com/kataras/iris/context.go:337 +0x64
github.com/kataras/iris.(*tree).serve(0xc082012a80, 0xc0821be000)
	C:/Users/shiena/go/src/github.com/kataras/iris/tree.go:185 +0x1e0
github.com/kataras/iris.(*Router).ServeRequest(0xc082010a50, 0xc0821be000)
	C:/Users/shiena/go/src/github.com/kataras/iris/router.go:196 +0x194
github.com/kataras/iris.(IRouter).ServeRequest-fm(0xc0821be000)
	C:/Users/shiena/go/src/github.com/kataras/iris/station.go:231 +0x46
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*Server).serveConn(0xc082038a00, 0xed5b20, 0xc0821b8000, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/server.go:1438 +0x752
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*Server).(github.com/kataras/iris/vendor/github.com/valyala/fasthttp.serveConn)-fm(0xed5b20, 0xc0821b8000, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/server.go:1176 +0x49
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0820e0380, 0xc082176280)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:224 +0x123
github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0820e0380, 0xc082176280, 0x7f0840, 0xc082176280)
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:183 +0x32
created by github.com/kataras/iris/vendor/github.com/valyala/fasthttp.(*workerPool).getCh
	C:/Users/shiena/go/src/github.com/kataras/iris/vendor/github.com/valyala/fasthttp/workerpool.go:185 +0x1f0
```

# Patch

```diff
diff --git a/context.go b/context.go
index c69d477..d1ca1b0 100644
--- a/context.go
+++ b/context.go
@@ -549,7 +549,7 @@ func (ctx *Context) ReadJSON(jsonObject interface{}) error {
        decoder := json.NewDecoder(strings.NewReader(string(data)))
        err := decoder.Decode(jsonObject)

-       if err != io.EOF {
+       if err != nil && err != io.EOF {
                return ErrReadBody.Format("JSON", err.Error())
        }

@@ -581,7 +581,7 @@ func (ctx *Context) ReadXML(xmlObject interface{}) error {
        decoder := xml.NewDecoder(strings.NewReader(string(data)))
        err := decoder.Decode(xmlObject)

-       if err != io.EOF {
+       if err != nil && err != io.EOF {
                return ErrReadBody.Format("XML", err.Error())
        }



```

**Comment by xpbliss** [comment]
Not using ```curl```, and make a .html with  json and try it

**Comment by kataras** [comment]
@shiena  excellent! fixed
