### ISSUE TITLE
panic response render with graceful

### ISSUE THREAD

**Issue by shiena** [kataras/iris#82]
# Environment

* commit 2b6b0fdd8abb1b4a48be7fde1b2763a003f7c1e4

# Reproduce

## Test code

```go
package main

import (
	"time"

	"github.com/kataras/iris"
	"github.com/kataras/iris/graceful"
)

func main() {
	routes := iris.New()
	routes.Get("/", func(c *iris.Context) {

		// only SetStatusCode is no problem
		// c.SetStatusCode(iris.StatusOK)

		c.JSON(iris.StatusOK, map[string]string{
			"foo": "bar",
		})
	})

	// Listen is no problem
	// routes.Listen(":8080")

	graceful.Run(":8080", time.Second*5, routes)
}
```

```
$ curl :8080
```

## error message

```
2016/05/03 03:10:56 panic: runtime error: invalid memory address or nil pointer dereference
Stack trace:
goroutine 37 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	C:/go/src/runtime/debug/stack.go:24 +0x87
github.com/valyala/fasthttp.(*workerPool).workerFunc.func1(0xc082154100, 0xc082167ee0)
	C:/Users/shiena/go/src/github.com/valyala/fasthttp/workerpool.go:207 +0x5a
panic(0x8eb580, 0xc082002090)
	C:/go/src/runtime/panic.go:443 +0x4f7
github.com/kataras/iris/render.(*Render).JSON(0x0, 0xc08216a000, 0xc8, 0x8160c0, 0xc08212e2d0, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/render/render.go:360 +0x1fd
github.com/kataras/iris.(*Context).JSON(0xc082140230, 0xc8, 0x8160c0, 0xc08212e2d0, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/kataras/iris/context_renderer.go:99 +0x62
main.main.func1(0xc082140230)
	C:/Users/shiena/go/src/graceful.go:19 +0xf1
github.com/kataras/iris.HandlerFunc.Serve(0xa72cd8, 0xc082140230)
	C:/Users/shiena/go/src/github.com/kataras/iris/handler.go:62 +0x2d
github.com/kataras/iris.(*Context).Do(0xc082140230)
	C:/Users/shiena/go/src/github.com/kataras/iris/context.go:171 +0x64
github.com/kataras/iris.(*tree).serve(0xc0821342a0, 0xc08216a000, 0xc08212c3c0, 0x1, 0x401)
	C:/Users/shiena/go/src/github.com/kataras/iris/tree.go:138 +0x1c5
github.com/kataras/iris.(*router).serveFunc(0xc0821341e0, 0xc08216a000)
	C:/Users/shiena/go/src/github.com/kataras/iris/router.go:192 +0x25d
github.com/kataras/iris.(*router).(github.com/kataras/iris.serveFunc)-fm(0xc08216a000)
	C:/Users/shiena/go/src/github.com/kataras/iris/router.go:104 +0x31
github.com/valyala/fasthttp.(*Server).serveConn(0xc082156000, 0xff1200, 0xc082138040, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/valyala/fasthttp/server.go:1452 +0x76e
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0xff1200, 0xc082138040, 0x0, 0x0)
	C:/Users/shiena/go/src/github.com/valyala/fasthttp/server.go:1183 +0x49
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc082154100, 0xc082130440)
	C:/Users/shiena/go/src/github.com/valyala/fasthttp/workerpool.go:224 +0x123
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc082154100, 0xc082130440, 0x7f3ba0, 0xc082130440)
	C:/Users/shiena/go/src/github.com/valyala/fasthttp/workerpool.go:183 +0x32
created by github.com/valyala/fasthttp.(*workerPool).getCh
	C:/Users/shiena/go/src/github.com/valyala/fasthttp/workerpool.go:185 +0x1f0
```

**Comment by kataras** [comment]
Yes this because renderer and router are setted on the ```Listen```, wait I will add the graceful inside the iris' server, things are changed after v2

**Comment by kataras** [comment]
@shiena I tested to my workstation now is working, can you test it to yours and tell me the results? Thanks for posting!

**Comment by shiena** [comment]
@kataras Thank you.
There was no problem to try to commit 7c57da4cfe0b512dcf8e8291daa98a6d793768cd .
And I recommend [mattn/go-colorable](https://github.com/mattn/go-colorable), if you want the color in cmd.
go-colorable package has many features than ansicolor package.

**Comment by kataras** [comment]
I know, but I am totally new with cmd, if you see [this repository](https://github.com/iris-contrib/iris) you will understand xD

**Comment by shiena** [comment]
@kataras Yes. It's working on Windows.
go-colorable has been imported from a number of packages.
https://godoc.org/github.com/mattn/go-colorable?importers

**Comment by kataras** [comment]
Hm okey, wait I finish with [this](https://github.com/kataras/iris/issues/81) I will continue the iris cmd work, I want to make an automatic updater with an option to turn off/on, and create a boilerplate project for fast startup with iris, thanks you!
