### ISSUE TITLE
Default WebSocket handler does not handle non-WS connections neat

### ISSUE THREAD

**Issue by mcsakoff** [kataras/iris#924]
```go
package main

import (
	"fmt"
	"github.com/kataras/iris"
	"github.com/kataras/iris/websocket"
)

func main() {
	app := iris.New()
	ws := websocket.New(websocket.Config{})

	app.Get("/ws", ws.Handler())

	ws.OnConnection(func(c websocket.Connection) {
		fmt.Print("WebSocket client connected")
	})

	app.Run(iris.Addr(":8080"))
}
```

Opening `http://localhost:8080/ws` in browser (simple GET) makes the application panic with nil pointer dereference:

```
[WARN] 2018/03/10 18:47 websocket error: websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header

WebSocket client connected[HTTP Server] http: panic serving [::1]:58676: runtime error: invalid memory address or nil pointer dereference
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc4204460a0)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1726 +0xd0
panic(0x1543f40, 0x192dfe0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/kataras/iris/websocket.(*connection).startPinger(0xc4205be140)
	/Users/username/go/src/github.com/kataras/iris/websocket/connection.go:322 +0x5f
github.com/kataras/iris/websocket.(*connection).Wait(0xc4205be140)
	/Users/username/go/src/github.com/kataras/iris/websocket/connection.go:546 +0x47
github.com/kataras/iris/websocket.(*Server).Handler.func1(0x1667780, 0xc4203d8360)
	/Users/username/go/src/github.com/kataras/iris/websocket/server.go:162 +0xcb
...
```

**Comment by mcsakoff** [comment]
It looks easy to fix but I'm not sure it doesn't break things below.

```diff
diff --git a/websocket/server.go b/websocket/server.go
index a08b3e1a..44120b90 100644
--- a/websocket/server.go
+++ b/websocket/server.go
@@ -147,6 +147,9 @@ func New(cfg Config) *Server {
 func (s *Server) Handler() context.Handler {
        return func(ctx context.Context) {
                c := s.Upgrade(ctx)
+               if c.Err() != nil {
+                       return
+               }
                // NOTE TO ME: fire these first BEFORE startReader and startPinger
                // in order to set the events and any messages to send
                // the startPinger will send the OK to the client and only
```

**Comment by kataras** [comment]
You didnt follow tha examples. First you do OnConnection and after cal of Handler, pleae try again and tell us the result.

**Comment by kataras** [comment]
Thanks @mcsakoff , normally you call the `OnConnection` first and after the `Handler()`, this will not panic but your fix is acceptable as well, good job!
